### ISSUE TITLE
error in parse_arg, "EXPR must be a length 1 vector"

### ISSUE THREAD

**Issue by r2evans** [opencpu/opencpu#104]
I'm getting an error when I pass a nested object where the top-level contains only one element, but no error if 2+ top-level elements.

``` javascript
ocpu.seturl('//localhost:9999/ocpu/library/utils/R')
ocpu.call('str', { object: { a: {b:1,c:2,d:3} } }, function(sess) { sess.getConsole(function(out) { console.log(out); }); })
// OpenCPU error HTTP 400
// EXPR must be a length 1 vector
// 
// In call:
// switch(x, true = return(as.expression(TRUE)), false = return(as.expression(FALSE)), 
//     null = return(as.expression(NULL)))
ocpu.call('str', { object: { a: {b:1,c:2,d:3}, e:4 } }, function(sess) { sess.getConsole(function(out) { console.log(out); }); })
// > str(object = object)
// List of 2
//  $ a:List of 3
//   ..$ b: num 1
//   ..$ c: num 2
//   ..$ d: num 3
//  $ e: num 4 
```

Oddly enough, it is not triggered if the single top-level element contains an array (or number or string) or a single-element named-array/object:

``` javascript
ocpu.call('str', { object: { a: {b:1} } }, function(sess) { sess.getConsole(function(out) { console.log(out); }); })
// > str(object = structure(list(a = structure(list(b = 1), .Names = "b")), 
// +     .Names = "a"))
// List of 1
//  $ a:List of 1
//   ..$ b: num 1 
```

I suspect this might actually be due to `jsonlite` but haven't hunted it down yet.

Triggered on single-user (win 7) and cloud (ubuntu 14.04). Win7 info below. (Note that I have updated `jsonlite` to 0.9.8 on both systems, but `opencpu` is of different versions. I don't believe that to be a huge factor in this case.)

``` r
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] methods   stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] r2utils_0.2

loaded via a namespace (and not attached):
 [1] brew_1.0-6         colorspace_1.2-4   devtools_1.5       digest_0.6.4      
 [5] evaluate_0.5.5     formatR_0.10       ggplot2_1.0.0      grid_3.1.0        
 [9] gtable_0.1.2       httpuv_1.3.0       httr_0.3           jsonlite_0.9.8    
[13] knitr_1.6.2        lattice_0.20-29    MASS_7.3-33        memoise_0.2.1     
[17] munsell_0.4.2      opencpu_1.4.1.99.2 pander_0.3.8       parallel_3.1.0    
[21] plyr_1.8.1         proto_0.3-10       Rcpp_0.11.1        RCurl_1.95-4.1    
[25] reshape2_1.4       scales_0.2.4       stringr_0.6.2      tools_3.1.0       
[29] whisker_0.3-2     
```

**Comment by lyndachina** [comment]
Hi Guys, 
I got a similar error now. 

I have used switch twice in my code. The first one works, however the second one got this error. 

My server.r is below: 
shinyServer(function(input, output) {
    
  output$plot1 <- renderPlot({ 
        
    
    DDCP<-function (HRdata, ndata, HRsuccess, TotEvents, propA = 0.5, propG = 0.5 ) 
    {
      fac <- (propA * (1 - propA))^(-1)
      fac2 <-(propG * (1 - propG))^(-1)
      res <- pnorm((log(HRsuccess) - log(HRdata))/(sqrt(fac/TotEvents + 
                                                          fac2/ndata)))
      return(res)
    }
#     source("DDCP.R")
    
    HRdata=input$HRdata
#     HRdata = seq(input$data[1],input$data[2],by=0.1)      
    ndata=input$ndata
    propG <- switch(input$propG , 
                   "1" = c(1),
                   "2" = c(0.5),
                   "3" = c(0.3333),
                   "4" = c(0.25) )

#     propG=0.5
    HRsuccess = seq(input$HRsuccess[1],input$HRsuccess[2],by=0.01)  
    TotEvents=input$TotEvents

    propA <- switch(input$propA , 
                   "1" = c(1),
                   "2" = c(0.5),
                   "3" = c(0.3333),
                   "4" = c(0.25) )
#     propA=0.5  
    #DDCP.2L.op1<-DDCP(0.65, ndata = 569, seq(0.60,1,by=0.01) , TotEvents = 106, propA = 2/3 )
    
    DDCP.2L.op1<-DDCP(HRdata, ndata, HRsuccess, TotEvents, propA , propG )
    
    DDCP.2L<-cbind(HRsuccess ,DDCP.2L.op1, HRdata, ndata,  TotEvents, propA , propG)
    DDCP.2L<-round(DDCP.2L,3)
    colnames(DDCP.2L)<-c("HRsuccess","op1","HRdata", "ndata",  "TotEvents", "propA" , "propG")
    DDCP_listing<-data.frame(DDCP.2L)
    attach(DDCP_listing)
    
#    DDCP_listing
    
   plot1<- plot(HRsuccess,op1,type="o",xlab = "HRsuccess",ylab = "DDCP",col="blue",ylim=c(0,1))
   
    #abline(v=0.717,lty=2,lwd=0.5,col="purple")
    #text(0.74,0.97,labels="HR=0.717 from EMILIA Asia",col="purple")
    #abline(v=0.65,lty=2,lwd=0.5,col="red")
    #text(0.65,0.75,labels="HR=0.65 from EMILIA",col="red")
    #abline(v=0.825,lty=2,lwd=0.5,col="blue")
    #text(0.825,1,labels = "consistency boundary HR = 0.825", col="blue")
    
    legend(x=0.85,y = 0.5,legend=c(paste("based on",input$ndata, "events")   ) )
   return(plot1)
          
  })
    
})



My ui.r is below:

shinyUI(fluidPage(
  
  titlePanel( textInput("title", label = h3("Please text the plot title"), 
                        value = "Enter text...") ) ,
  fluidRow(
    column(3, 
           wellPanel(
             sliderInput("HRdata", label = h5("Please define prior HR"),
                         min = 0, max = 1.5, value = 0.65),
             
             
             numericInput("ndata", 
                          label = h5("Please input prior number of event(Numeric)"), 
                          value = 569 ) ,  
             
             selectInput("propG", label = h5("Please choose prior Randomization Radio"), 
                         choices = list("1:1" = 1, "1:2" = 2, "1:3" = 3,"1:4"=4), selected = 2)
             
             
             
             
           ),
           wellPanel(
             sliderInput("HRsuccess", label = h5("Please define posteriror HRSuccess"),
                         min = 0, max = 1.5, value =c(0.6,1) ),
             
             
             numericInput("TotEvents", 
                          label = h5("Please input posteriror number of event(Numeric)"), 
                          value = 106 ) , 
             
             
             selectInput("propG", label = h5("Please choose posteriror Randomization Radio"), 
                         choices = list("1:1" = 1, "1:2" = 2, "1:3" = 3,"1:4"=4), selected = 2)
             
             
           )
    ),
    
    column(9,
           mainPanel(plotOutput("plot1"))
#            ,
#            wellPanel(
#              span("DDCP Based on HR for Success")
#                      )
          )
    
  ) 
  
)

)


Looking forward to your reply. Thanks in advance.

**Comment by jeroenooms** [comment]
@lyndachina this repo is for opencpu issues, this looks like a programming error on your hand. You get this error when the first argument of a switch is NULL, so check the value for `input$propG` and `input$propA`.

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
