### ISSUE TITLE
fromJSON and the simplify* arguments in OpenCPU

### ISSUE THREAD

**Issue by MeiResearchLtd** [opencpu/opencpu#112]
Hello, 

Is there a way to force opencpu to call fromJSON with the simplify\* arguments set to FALSE when parsing a POST request?

**Comment by jrdnmdhl** [comment]
Sorry to revive this issue, but I do believe it is important not to force the simplify arguments to TRUE .  There is a whole class of nested list type structures which map very well between R and JSON.  Dealing with these is a lot easier when the structure is preserved between the two languages than when it is radically changed.

As an example, here is a gist showing a javascript object defining the structure and parameters of a model I am coding in R.  When passed as a JSON argument, it gets a bit mangled and the resulting object in R is a bit of a pain to work with.

As an alternative, I think I would make sense to think about how to build in some optional parameters avoid this kind of behavior.
