### ISSUE TITLE
weird error handling ... arguments

### ISSUE THREAD

**Issue by alexdeng** [opencpu/opencpu#114]
I wrote a general function to rander R script or R markdown with access to arguments in ... . I used pryr's named_dots to capture the unevaluated arguments in ... and then use eval to assign these arguments to their name so they can be seen when rmarkdown render the script. The following function  render works well offline when I test locally. However, when I published in opencpu, and I hit some weird error which I think is related to how opencpu handles arguments. 

If I provide opencpu with 
{
text: 'ls()',
ext='R',
a = {"b":1,"c":1}
}

I will get an error saying when doing eval object a is not found. 

Somehow this issue is gone when I don't use ..., the render2 function below works well. 
## I'll take a look at the source code but want to get your quick opinion first. 

render = function(text, ext='Rmd',...){
  inputfile = paste0("input.",ext)
  writeLines(text, con=inputfile)
  import_dots(...)
  render(input = inputfile,output_options=list(self_contained=TRUE),output_file="output.html")
  invisible()
}

render2 = function(text, ext='Rmd',injectData){
  inputfile = paste0("input.",ext)
  writeLines(text, con=inputfile)
  render(input = inputfile,output_options=list(self_contained=TRUE),output_file="output.html")
  invisible()
}

import_dots = function(...){
  nameddots = pryr::named_dots(...)
  #import ... and assigned evaluated arguments
  for(name in names(nameddots)){
    assign(name, eval(nameddots[[name]]),envir = parent.frame())
  }
}

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
