### ISSUE TITLE
Debugging info for R process death

### ISSUE THREAD

**Issue by flammit** [opencpu/opencpu#130]
Hi Jeroen,

I've gotten around the data loading issues with increased temp space.  I have a 145MB csv that I've loaded up successfully into an opencpu session, but when I try to use it in a regression call I get:

```
R call failed: process died.
```

Is there any place I can look for some additional logging on why the process may have failed?  I've increased memory using the server.conf parameters (rlimit.as = 16e9) to avoid those issues.

Thanks,
Francis

**Comment by jeroenooms** [comment]
Can you try raising `rlimit.fsize` in `server.conf`?

**Comment by flammit** [comment]
The rlimit.fsize is set to 16e9 as well.

Sorry I should've provided the timestamps as it might be indicative of something:

```
13:27:26,419 DEBUG [Thread-10//ParallelOpenCPUDriver] - [loadDataFrameGetOutput] Loading data frame into OpenCPU
13:28:09,611 DEBUG [Thread-10//ParallelOpenCPUDriver] - [sendRequestGetOutput] Output from OpenCPU:
/ocpu/tmp/x00791c643d/R/.val
/ocpu/tmp/x00791c643d/stdout
/ocpu/tmp/x00791c643d/source
/ocpu/tmp/x00791c643d/console
/ocpu/tmp/x00791c643d/info
/ocpu/tmp/x00791c643d/files/data.csv
/ocpu/tmp/x00791c643d/files/DESCRIPTION

13:28:09,611 DEBUG [Thread-10//ParallelOpenCPUDriver] - [runModel] Sending modeling request to OpenCPU
13:28:09,648 DEBUG [Thread-10//ParallelOpenCPUDriver] - [sendRequestGetOutput] Output from OpenCPU:
R call failed: process died.

13:28:09,649 WARN  [Thread-10//ParallelOpenCPUDriver] - [runModel] Error running regression model runSurvivalSurvfit
```

(The R process fails relatively quickly after the data load).

**Comment by jeroenooms** [comment]
Are there any notes in `/var/log/kern.log` ?

**Comment by flammit** [comment]
I'm running this in a docker container (Ubuntu 14.04 + opencpuserver).  Nothing relevant in the host kern.log (which is also Ubuntu 14.04) or in the docker logs.  In apache's error.log, I see a bunch of: 

```
[Thu Jan 08 18:53:42.568658 2015] [:error] [pid 538] [client 172.17.42.1:35695] rApache Notice!
[Thu Jan 08 18:53:43.854738 2015] [:error] [pid 539] [client 172.17.42.1:35697] rApache Notice!
[Thu Jan 08 18:53:45.145378 2015] [:error] [pid 540] [client 172.17.42.1:35697] rApache Notice!
```

But this happens regardless of success or failure.

**Comment by jeroenooms** [comment]
Those rapache notices are harmless. So it does work for smaller files? Around what size does it break?

**Comment by flammit** [comment]
It certainly works for files on the order of ~1-10MB, but I don't have an exact breakdown / distribution of what works.

Curious, I can successfully run the following now:

```
curl http://localhost:8006/ocpu/library/base/R/summary -d "object=x00791c643d"
```
on that previous session referenced above as well as the regression call I was running.

Is it possible that there's some file flushing that is happening which prevents a large session from being used immediately after the session ids are returned?

**Comment by jeroenooms** [comment]
No, files are saved immediately. The "process has died" error [comes from RAppArmor](https://github.com/jeroenooms/RAppArmor/blob/master/R/eval.secure.R#L170) which probably means that something is going wrong when the process is forked.

It might be related to Docker, I haven't tested it that much yet, and docker is known for conflicting with kernel features. Would it be possible for you to test if this problem appears outside of docker? You could install opencpu on the host, or inside kvm (instead of docker), or just spin up a quick EC2 instance or something...

**Comment by flammit** [comment]
Yeah I think we're going to just spin up a separate EC2 instance to test.  I'll let you know if we still see the same problem.

**Comment by flammit** [comment]
Unfortunately no luck on a separate EC2 instance, I get the same behavior.

As a workaround, I'm going to add retrying the regressions with some fixed sleep intervals (5s, 20s, 60s) after getting error output like "R call failed: process died".  Hopefully this helps.

**Comment by jeroenooms** [comment]
Can you check /var/log/kern.log on your ec2 instance?

**Comment by flammit** [comment]
I checked it, but unfortunately there's nothing in kern.log that happens when the call fails.

**Comment by jeroenooms** [comment]
I doubt the sleep intervals will help. A better design might be to store your data in a database (e.g. mysql server) and read it into R with RMySQL. Instead of posting a 145mb csv file, the client can post credentials to the RMySQL server (or you can hardcode them). Usually we don't pass around this much data in http parameters.

I'll try to find some time to look into this exactly problem soon. It looks like it might be tricky though.

Thanks for reporting this.

**Comment by flammit** [comment]
No worries.  Thanks for the quick responses.  In all cases, a retry after 1s sleep actually succeeds, so that might help your diagnosis.

**Comment by jeroenooms** [comment]
Oh wow interesting. That must be something on the hardware level buffering the disk write then.

**Comment by jdanielnd** [comment]
I'm running into the `R call failed: process died` error with very small requests. The only data passed is a vector of 30 to 50 integers.

If I setup a queue of 5000 posts to an OpenCPU running on Ubuntu c4.large instance it just happens with the first 5 or 10 requests. After that, everything runs fine. Also, if I retry the requests with the error, it goes well too.

Maybe it's something related to a sudden flow of requests?

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
