### ISSUE TITLE
Error while loading package 'zoo' or namespace

### ISSUE THREAD

**Issue by liferayhacks** [opencpu/opencpu#132]
Hi,

I keep on getting follwing error when trying to invoke my custom API
package or namespace load failed for 'zoo'
I am able to look at package information by calling /ocpu/library/zoo/
but when i do /ocpu/library/zoo/R then again I get the above error. 
Am i missing something here

**Comment by jeroenooms** [comment]
Which version of OpenCPU are you running? Did you try restarting the server? 

   sudo service apache2 restart

**Comment by liferayhacks** [comment]
I am using opencpu 1.4 and i have restarted server many times.

**Comment by jeroenooms** [comment]
Is there anything in the apache2 or opencpu error logs?

This error often appears when some dependency is missing.

**Comment by liferayhacks** [comment]
suprisingly i dont see any error in the apache logs or opencpu logs.

Shoaib

**Comment by jeroenooms** [comment]
What do you see when you try:

    curl https://127.0.0.1/ocpu/library/base/R/identity/console -d "x=try(library(zoo))"

**Comment by liferayhacks** [comment]
it gives me this output

identity(x = try(library(zoo)))

**Comment by jeroenooms** [comment]
No error? That is strange. What about:

    curl https://127.0.0.1/ocpu/library/base/R/identity/console -d "x=zoo::zoo()"

or

    curl https://127.0.0.1/ocpu/library/base/R/identity/console -d "x=try(zoo::zoo())"

**Comment by liferayhacks** [comment]
here is the output for second commans 
identity(x = try(zoo::zoo()))
First command does not give any output.
I believe it is some problem with my R environment. Let me try setting up on another system. Thanks a lot for your prompt response. I really appreciate it.

Shoaib

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
