### ISSUE TITLE
Can't install github package if it requires another package from github

### ISSUE THREAD

**Issue by moosilauke18** [opencpu/opencpu#137]
Basically I have a github package that requires another package from github.  Let's say `package B` imports `package A`.  

If I try to install `package B` it fails.  I can install `package A` and use it, but if I try to install `package B` again it still fails.  My guess is `devtools` tries to load the dependencies it can't find the location under `/tmp/ocpu-www-data`.

**Comment by jeroen** [comment]
You can do this by setting a `Remotes` field in your package `DESCRIPTION`. See devtools documentation for details.
