### ISSUE TITLE
Personal user library not available

### ISSUE THREAD

**Issue by jrowen** [opencpu/opencpu#139]
I am running into the error `User jrowen not found.` when trying to access the libraries under a specific user name, `http://.../ocpu/user/jrowen/library/`.  The global url, `.../ocpu/library/`, works fine.

The server has RStudio and shiny installed, and the latter is set-up to allow users to host their own apps (`user-dirs` flag).  I'd like to set-up OpenCPU to also take advantage of the user-specific libraries.  I've confirmed that the `~/R` (link) is marked as public readable.  The server is running RHEL 6.6 and SELinux is disabled.

Installing libraries under the global user is not possible on this machine, as it will interfere with the shiny set-up.  Should a user's personal library be available under this set-up?

**Comment by jeroenooms** [comment]
What do you see for:

    curl http://yourserver/ocpu/library/base/R/identity/json -d "x=opencpu:::listallusers(T)"

**Comment by jrowen** [comment]
I don't see`jrowen' listed but I do see `apache` and `rstudio-server` (among others).  The server is set-up to use Active Directory to authenticate users.

**Comment by jrowen** [comment]
I haven't yet found a way to list all AD users set-up on the machine, but on a one-off basis, it does look like the `id [user]` command returns details if the user is set-up.

**Comment by jrowen** [comment]
A possible fix could be to update the user check in [`httpget_user`](https://github.com/jeroenooms/opencpu/blob/master/R/httpget_user.R) to use a function like
```R
checkuser = function(username, user.only = TRUE) {
  if(username %in% opencpu:::listallusers(FALSE)){
    return(TRUE)
  } else {
    out <- try(read.table("/etc/sysconfig/authconfig", sep="=", as.is=TRUE))
    if((is.null(attr(out, "status")) || attr(out, "status") == 0) 
       && !is.null(out$V2[out$V1 == "USESSSD"]) && 
         out$V2[out$V1 == "USESSSD"] == "yes"){
      out <- system2("id", username, stdout=TRUE)
      if(is.null(attr(out, "status")) || attr(out, "status") == 0){
        if(isTRUE(user.only)){
          uid = as.numeric(regmatches(out, regexpr("(?<=uid=)[0-9]*", out, perl=TRUE)))
          return(uid > 999 && uid < 65534)
        }
        return(TRUE)
      }
      return(FALSE)
    }
  }
}
```

**Comment by jrowen** [comment]
I was able get past the first error with the updated function above, but am now seeing
```
Could not find or access home directory of user jrowen
```
It looks like the problem is with `path.expand` not resolving ~
```
$ curl http://.../ocpu/library/base/R/identity/print -d "x=path.expand(paste0('~', 'jrowen'))"
[1] "~jrowen"
```

**Comment by jeroenooms** [comment]
Is your package library in the default location? `/home/jrowen/R/x86_64-pc-linux-gnu-library/3.1/` ?

**Comment by jrowen** [comment]
My package library is in the default location, `/home/jrowen/R/x86_64-redhat-linux-gnu-library/3.1`, and is accessible by shiny and RStudio.

I think I've finally got this working.  I had to also update `opencpu:::homedir` with another check
```
#third method
  home <- path.expand(paste0("/home/", username))
  if(file.exists(home)){
    return(home)
  }
```
I wasn't able to find another way to get `~` to expand to `/home`.  I also tried added `HOME='/home'` to `/etc/opencpu/Renviron`, but that didn't work.

This is probably a bit of an outlying situation, but anyone using Active Directory authentication (or related) will probably run into the same problem.  

Any chance of these fixes (or something similar) making it into a future release?

**Comment by jeroenooms** [comment]
Sure if you send a PR I will review it

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
