### ISSUE TITLE
Restart the opencpu service when a preloaded package gets built

### ISSUE THREAD

**Issue by fjukstad** [opencpu/opencpu#152]
Hey! 

I'm currently developing a R package that is preloaded by the opencpu service. If I update and build the package I need to manually restart the opencpu service to make the changes available. It would be great if the opencpu service could restart automatically whenever I build the package.

**Comment by jeroenooms** [comment]
Why do you think it needs to restart? Did you just try refreshing in the client?

**Comment by fjukstad** [comment]
So far I've had to manually restart it. I'm running a Docker container with both RStudio and OpenCPU, developing the package in RStudio and using the API Explorer to try out new functions etc. If I add a new function to the R package, the OpenCPU server returns a HTTP 400 Bad Request until I restart the opencpu service. 

We'll maybe get the same problem if the lattice or ggplot2 packages are updated?

**Comment by jeroenooms** [comment]
Are you reinstalling a package that has been preloaded? What error text do you get in the http 400?

**Comment by fjukstad** [comment]
Yes that is correct, reinstalling a preloaded package.

If I add a function `testfunc` to my package, install it and do a HTTP GET to the `../library/mypackage/R/testfunc` endpoint, I get back:

```
object 'testfunc' not found

In call:
get(reqobject, paste("package", reqpackage, sep = ":"), inherits = FALSE)
```
 and a HTTP 400 Bad Request with the header:
```
X-ocpu-time: 2015-07-08 12:59:47 UTC
Date: Wed, 08 Jul 2015 12:59:47 GMT
Content-Encoding: gzip
Server: Apache/2.4.10 (Debian)
X-ocpu-locale: en_US.UTF-8
Vary: Accept-Encoding
X-ocpu-r: R version 3.2.0 (2015-04-16)
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, X-ocpu-session, Content-Type, Cache-Control
X-ocpu-version: 1.4.6
X-ocpu-server: rApache
Connection: close
Content-Type: text/plain; charset=utf-8
Access-Control-Allow-Headers: Origin, Content-Type, Accept, Accept-Encoding, Cache-Control
Content-Length: 116
```

**Comment by jeroenooms** [comment]
Ah yes if you have the package preloaded than you need to restart the server. One easy way around this is to not preload your package during development.

**Comment by fjukstad** [comment]
Allright, maybe I'll give it a go. Thanks!

**Comment by jeroenooms** [comment]
Of course you can still preload the dependences if your package to make things a bit faster while developing :)

**Comment by dpk3993** [comment]
Hi jeroenooms 
Please help to fix all time newly generated /ocpu/tmp/**x0a175ebb2e**/R/.val  .
thanks 
Deepak

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
