### ISSUE TITLE
Ohmage and OpenCPU on Fedora21

### ISSUE THREAD

**Issue by nix-xin** [opencpu/opencpu#158]
I noticed there wasn't a RPM for ohmage-viz so I installed the OpenCPU rpm on the same server running Ohmage. Additionally, I installed the R package for Mobilize so that I can take advantage of the visualizations in Ohmage Explore Data. I cant seem to understand how apache is supposed to interface with OpenCPU. Are there instructions for setting Ohmage and OpenCPU on Fedora21? Any help is appreciated.

**Comment by otter-design-inc** [comment]
Actually I just found https://github.com/jeroenooms/Mobilize/blob/master/help/install.centos.txt
I will give these instructions a try. Thanks for providing these.

**Comment by otter-design-inc** [comment]
Ok, so I'm not any further than I was before this post. I was hoping the instructions for CentOS were similar for Fedora, but I don't this that's the case. 
The instructions for installing ohamge-viz on Ubuntu were pretty straight forward when setting/unsetting the value for "visualization_server_address" to http://127.0.0.1/R/call/Mobilize 
After setting the Location directive in rApache to <Location /R> I thought this would find the location to necessary R package Mobilize. But here's where I'm stuck.
Am I not setting the Location directive correctly.
<Location /R>
 SetHandler r-handler
 RFileHnadler /path/to/R/Mobilize
</Location>
Can someone help with this issue?
