### ISSUE TITLE
How to read a local file on cloud?

### ISSUE THREAD

**Issue by alliquot** [opencpu/opencpu#162]
Dear Jeroen,
I have some SQL scripts and RMD reports just to keep things separated from R code. I'd like to load them at runtime and process.
When I'm trying to load them like file("somefile.sql") or render("somereport.rmd"), I receive a message:

file 'Report1.rmd' does not exist
In call:
tools::file_path_as_absolute(input)

How to read "local" files (CSV, rmd, sql etc)?

EDIT:
OK, I've found the file at /usr/local/lib/R/site-library/MyLib/www/Report1.rmd

but faced another error:
cannot open the connection
In call:
file(file, ifelse(append, "a", "w"))

I guess this comes from knitr or rmarkdown. Is this possible to run rmarkdown::render on the server by providing a name of a file containing the report?

**Comment by jeroenooms** [comment]
To read files from within a package use the `system.file` function, for example:

    read.csv(system.file("www/myfile.csv", package = "mypackage"))

**Comment by jeroenooms** [comment]
Note that you can also POST to the markdown script directly, for example:

    curl -X POST http://public.opencpu.org/ocpu/library/jsonlite/doc/json-aaquickstart.Rmd

**Comment by alliquot** [comment]
Dear Jeroen, thank you very much for the answer.
Unfortunately, it didn't solve the issue: 

for rmarkdown::render:
"cannot open the connection
In call:
file(file, ifelse(append, "a", "w"))"

for knitr::knit2html
"subscript out of bounds
In call:
m[[1]]"

Do you have any idea what's wrong?

I have to run the report inside R code as it is only a part of a greater task. I could chain calls in JS, but this will move all the logic to the client and JS. Moreover I don't know which engine you use for processing Rmd - knit2html or rmarkdown:render or perhaps different one. I have to do it with rmarkdown:render with parameters depending on other steps of the task to obtain a Word document.

**Comment by stla** [comment]
I have a similar problem. I'm using system.file(). 
Did you solve this issue, @alliquot ?

**Comment by stla** [comment]
I've solved my issue. The problem was due to the intermediate files directory. One has to set it with the option `intermediates_dir`:
```
 rmarkdown::render(system.file(package = "ocpusimplereg", "templates", "regression.Rmd"),
                           output_dir = getwd(),
                           intermediates_dir = getwd())
```
