### ISSUE TITLE
directlabels fails to draw using opencpu

### ISSUE THREAD

**Issue by josephguillaume** [opencpu/opencpu#165]
Dear Jeroen,

I've come across a potential bug when adding labels to a ggplot2 plot using the directlabels package.
The labels are not drawn, but if I download the .val as Rdata, it plots correctly interactively or to png.
I've had the same problem using the direct.label function and using geom_dl.

Is it possible this problem is related to how opencpu handles plotting?

I've tried to put together a reproducible example here:
http://jsfiddle.net/u5zfLxgp/2/
The example is taken directly from the directlabels package. When the code is run, the intended behaviour is for it to put labels on the plot.
I've also included a link to download the corresponding .val object.

Thanks for any advice,

Best,

Joseph

**Comment by josephguillaume** [comment]
A small update.
From an interactive session, the correct plot can be obtained by asking for the object in png format directly (/R/object/png). I understands this actually replots the object (httpget_object).

This doesn't work on the public server.  The error is:
could not find function "dlgrob"
In call:
get(x, envir = this, inherits = inh)(this, ...)
http://jsfiddle.net/u5zfLxgp/3/

The problem therefore appears to be that the directlabels package is not available when rendering the png.
The difference in behaviour appears to be that:
- using httpget_object directly re-evaluates the ggplot2+directlabels object, which fails
- using httpget_session_graphics uses the recorded plot, which apparently does not fail, but does not show the labels either

I notice that ggplot2 and lattice are currently explicitly reloaded.
I assume other packages aren't reloaded in the interest of computational efficiency.
What would the preferred mechanism be to allow arbitrary graphics packages like directlabels to be reloaded as necessary?

Here's another reproducible example:

library(directlabels)
library(ggplot2)

scatter <- qplot(jitter(hwy),jitter(cty),data=mpg,colour=class,
                 main="Fuel efficiency depends on car size")
object=direct.label(scatter)
output=evaluate::evaluate(input="print(object)")
plot=print(object)
unloadNamespace("directlabels")
print(output) 
print(object)
library(directlabels)
print(output)
print(object)

**Comment by jeroenooms** [comment]
Thanks. This is a known problem unfortunately. The `recordPlot` / `replayPlot` system is not perfect and sometimes fails when code on the displaylist assumes packages are attached but they are not. Paul Murrell has made substantial improvements on `recordPlot` in R 3.3. 

The easiest fix would be if the author of `directlabels` would add a `library(directlabels)` call to the display list, or alternatively explicitly call `directlabels::geom_dl`. If you run your own opencpu server and really want this to work you could configure it to always run `library(directlabels)` in every session.

**Comment by josephguillaume** [comment]
Thanks.
I don't think calling directlabels::geom_dl directly would be enough, because calculations occur within the generic drawDetails.dlgrob method, calling other functions within the directlabels package. I'm not sure if there's a way to specify the package in which to find the definition of a generic method.

However, I can confirm that adding library(directlabels) to the display list works.
At run time, this can be achieved using a trace call:
trace(directlabels::geom_dl,quote(recordGraphics(library(directlabels),list(),.GlobalEnv)),at=list(c(4,3,3,3,3,3,7)))

Example:
http://jsfiddle.net/u5zfLxgp/6/

I think giving the package responsibility to register itself with recordGraphics is a reasonable solution, but for consistency it seems it should probably apply to ggplot2 and lattice, which are currently treated as special cases within opencpu.

**Comment by jeroenooms** [comment]
Yes hadley is aware of this and has implemented the same fix in ggplot2 I think. In your case perhaps a simpler workaround would be to use the `plot.new` hook. Something like:

```r
setHook("plot.new", function(){
  recordGraphics(library(directlabels), list(), .GlobalEnv)
})
```

**Comment by josephguillaume** [comment]
The `grid.newpage` hook works with the example I gave, but I don't think `plot.new` gets called for ggplot2.

It seems `setHook` should be the official solution for the time being.
The `replayPlot` help explicitly says: "Recorded plots can not be used as a permanent storage format for R plots. There were extensive changes in R 3.0.0, and now only plots from the current session can be replayed."
As I understand it, opencpu is using recorded plots as a means of storage and uses `fixplot` to explicitly allow replaying between sessions.
At the moment, other packages would therefore be fixing this problem mainly for opencpu's benefit.
Ultimately, I think there does need to be a permanent storage format for R plots, and opencpu is right to use `evaluate`/`recordPlot` that way, but changes to directlabels should be postponed until recorded plots can more widely be used as a permanent storage format.

I'm happy to treat this problem as solved in the meantime.

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this is still a problem in OpenCPU 2.0.
