### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by alliquot** [opencpu/opencpu#166]
Dear Jeroen,

I'm trying to measure the performance of my simple testing setup on my laptop. I'm using JMeter. For single user it returns request in 400ms. For 10 users it is 4.5 sec. But when I changed number of users to 30, it started raising error 400 "Bad request".

What does it mean exactly: is there a connection limit or is there a software problem?

My function uses DBI to connect to MySQL and retrieve 5 records, then it closes connection and returns simple data.frame(id=ids_read_from_db, name=names_read_from_db)

I think I need a load balancer for better handling requests, but what about error 400?

---

OK, I've found additional information in the JMeter output - R died: 

```
Response code: 400
Response message: Bad Request

Response data: "R call failed: process died.
```

---

Exemplary output from performance testing:

```
Sample Start time   Thread name        Label   Sample time   Status   Bytes   Latency   Connect time (ms)
1   05:15:23.792    Thread Group 1-2    HTTP Request    3938    Success 982 3938    0
2   05:15:23.848    Thread Group 1-3    HTTP Request    4310    Success 982 4310    0
3   05:15:23.905    Thread Group 1-1    HTTP Request    4431    Success 982 4431    0
4   05:15:24.049    Thread Group 1-4    HTTP Request    4687    Success 982 4687    0
5   05:15:23.988    Thread Group 1-5    HTTP Request    4752    Success 982 4752    0
6   05:15:24.079    Thread Group 1-8    HTTP Request    4883    Success 982 4883    0
7   05:15:24.330    Thread Group 1-10   HTTP Request    4950    Success 982 4950    0
8   05:15:24.275    Thread Group 1-6    HTTP Request    5029    Success 982 5029    0
9   05:15:24.331    Thread Group 1-7    HTTP Request    5025    Success 982 5025    0
10  05:15:24.284    Thread Group 1-9    HTTP Request    5130    Success 982 5130    0
11  05:15:24.436    Thread Group 1-14   HTTP Request    5044    Warning 645 5044    0
12  05:15:24.332    Thread Group 1-12   HTTP Request    9167    Success 982 9167    0
13  05:15:24.356    Thread Group 1-11   HTTP Request    9402    Success 982 9402    0
14  05:15:24.384    Thread Group 1-13   HTTP Request    9447    Success 982 9447    0
15  05:15:24.568    Thread Group 1-15   HTTP Request    9394    Success 982 9394    0
16  05:15:24.608    Thread Group 1-18   HTTP Request    9434    Success 982 9434    0
17  05:15:24.874    Thread Group 1-20   HTTP Request    9210    Warning 645 9210    0
18  05:15:24.616    Thread Group 1-17   HTTP Request    12046   Success 982 12046   0
19  05:15:24.624    Thread Group 1-16   HTTP Request    12838   Success 982 12838   0
20  05:15:24.657    Thread Group 1-19   HTTP Request    12881   Success 982 12881   0
```

**Comment by jeroenooms** [comment]
Are you sure you have sufficient hardware to run many R procs? Also try raising some of the `rlimit` values in `/etc/opencpu/opencpu.conf`. In particular `rlimit.nproc` will limit the number of concurrent requests.

**Comment by alliquot** [comment]
Well, I installed it on the latest Debian (stable) placed on VM. I'm looking at resource monitor and the memory consumption is pretty low. No, this is not the case. R is "killed" from time to time - it doesn't matter if I run the service by hand from webbrowser (single user) or via JMeter (simulating 20 users). 20 times it may work OK and 21st - it will fail. Randomly. Sometimes fails once by once, sometimes 50 times it works without any problems. I have no idea what's going wrong.

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this is still a problem in OpenCPU 2.0.
