### ISSUE TITLE
[SOLVED] How to prevent user functions and files from being displayed?

### ISSUE THREAD

**Issue by alliquot** [opencpu/opencpu#168]
Dear Jeroen,

Is there a way to prevent user functions and some files from being displayed (via GET) in a web browser? I'd like to save some information in a config file, but don't want others to see its content. The same pertains to functions, which contain authorization code, which must not be visible to the "wide audience"

Yes, I know that someone can get the code other way, but it involves more efforts. I'll try to play with htacess file.

---

OK, I've found a way of how to prevent displaying the body of a function via GET.
In the .../sites-available/opencpu.conf, in the <Location /ocpu> section I added the following code:

```
<LimitExcept POST>
    Require all denied
</LimitExcept>
```

---

No, this disables everything :/ There must a be a way of preventing displaying only functions...

---

Also tried to overload print.function and body functions, but - however this works from console - doesn't work from server...

Have no further ideas.

**Comment by alliquot** [comment]
OK, this works for GET.

    <Location /ocpu/library/*/R/*/print>
    	SetHandler r-handler
    	    <Limit GET HEAD POST>
    		AllowOverride None
    		Require all denied
    	    </Limit>
    </Location>

However it doesn't work for POST. It is important, because one can POST with a function as a parameter (also print.function should be blocked). The same for **body** and **fix**

**Comment by rubenarslan** [comment]
[Very similar problem](https://github.com/jeroenooms/opencpu/issues/157), but we did it in nginx instead of in Apache. HTH

**Comment by alliquot** [comment]
OK, I solved it by using two mod_rewrite rules.

It prevents from displaying the function's body by:
- denying GET queries which turn into an URL like this: **_/ocpu/library/some_library/R/some_function/print_**

Test:
GET http://192.168.1.33/ocpu/library/TestPackage/R/AuthenticateUser

_**Forbidden
You don't have permission to access /ocpu/library/TestPackage/R/AuthenticateUser/print on this server.
Apache/2.4.10 (Debian) Server at 192.168.1.33 Port 80**_

Good news: it doesn't prevent from retrieving results via GET, so ocpu works as expected:
POST http://192.168.1.33/ocpu/library/TestPackage/R/AuthenticateUser
params: login="somelogin", password="somepassword")

    /ocpu/tmp/x0731dc6935/R/.val
    /ocpu/tmp/x0731dc6935/stdout
    /ocpu/tmp/x0731dc6935/source
    /ocpu/tmp/x0731dc6935/console
    /ocpu/tmp/x0731dc6935/info
    /ocpu/tmp/x0731dc6935/files/DESCRIPTION

GETtting the result works as expected:
GET http://192.168.1.33/ocpu/tmp/x0b6ec60575/R/.val/print

    {"result":[{"UserName":"some user"....}

- denying POST queries to libraries other than "white listed" ones. POST queries to any other library, including base (base::print) will result in 403 error (forbidden).

Let's try to "print" the content of the AuthenticateUser function:

POST http://192.168.1.33/ocpu/library/base/R/print
params: x=TestPackage::AuthenticateUser 

_**Forbidden
You don't have permission to access /ocpu/library/base/R/print on this server.
Apache/2.4.10 (Debian) Server at 192.168.1.33 Port 8**_

Both rules:

    	<Location /ocpu>
		SetHandler r-handler
		RHandler opencpu:::rapachehandler
		SetOutputFilter DEFLATE
		AllowOverride all

		RewriteEngine On
		RewriteCond %{REQUEST_METHOD} POST
		RewriteCond %{REQUEST_URI} !/ocpu/library/(MyWhitelistedLibs.*|MyCommonLib)/.* [NC] 
		RewriteRule .* - [F,L]

		RewriteCond %{REQUEST_METHOD} GET
		RewriteCond %{REQUEST_URI} /ocpu/library/.*/.*/print [NC] 
		RewriteRule .* - [F,L]
	</Location>

I don't know if there are other ways to display the content of a function, but this solution makes it difficult.
