### ISSUE TITLE
Bug? in version opencpu-0.5

### ISSUE THREAD

**Issue by tjhgit** [opencpu/opencpu#169]
Hi Jeroen,

there seems to be a bug in the 0.5 version - or at least under the internet explorer version 11 the warning for newbies fails even though I am calling jquery - 1.10.2 before opencpu. Should I upgrade to a newer version of jquery? In case of yes, how would I do this?

Regards,
Thomas.

**Comment by parisni** [comment]
Hi, 

I do still have this problems with ie11 & ocpu-0.5.js

Thanks

**Comment by jeroen** [comment]
I have tested the [example apps](https://www.opencpu.org/apps.html) in Internet Explorer and they all seem to work so I think this is solved. Please open a new issue if you still experience problems.
