### ISSUE TITLE
use scikit-learn in the markdownapp example

### ISSUE THREAD

**Issue by yanji84** [opencpu/opencpu#170]
I deployed the markdownapp in my own server. On the server I have installed scikit-learn and I verified that I can import it correctly when running python from the server. However, when I import scikit-learn from python code block in markdownapp, it is saying that module sklearn is not installed.

I also tried to run knit2html from the server directly with the same python code, it can import sklearn without any issue. This means something in opencpu does not work correctly.

Please help me for any insight on this. Thanks!

**Comment by jeroenooms** [comment]
Can you try to make a reproducible example? I don't know what sklearn is.

**Comment by yanji84** [comment]
From https://158.85.79.185/ocpu/library/rmarkdown/www/

This is the whole markup,

```
```{r engine='python', highlight=TRUE}
from sklearn import datasets
```

And this is the output

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sklearn

I have installed the sklearn package locally and if I run knit2html from r on the server directly, it has no issue finding the package

**Comment by jeroenooms** [comment]
Looks like you're running CentOS. Do you have SELinux enabled?

**Comment by yanji84** [comment]
I am running on Centos with SELinux disabled

**Comment by jeroen** [comment]
Cleaning up old issues. Feel free to open a new issue if this problem still exists in OpenCPU 2.0.
