### ISSUE TITLE
OpenCPU Runtime logs

### ISSUE THREAD

**Issue by pjpastrana** [opencpu/opencpu#171]
I started an opencpu$start() instance locally on my machine.
I have a webapp calling the service and the R script invoked by the service starts but does not finish and fails after a few seconds. I know it started because I can see the processes and resources under Windows Task Manager.

Does OpenCPU generate any type of runtime logs on Windows OS?
Thanks.

**Comment by jeroen** [comment]
The single user server in OpenCPU 2.0 is now much more verbose. I think that should help!
