### ISSUE TITLE
Install opencpu without updating R version

### ISSUE THREAD

**Issue by SampurnR** [opencpu/opencpu#180]
In the following steps:

```
#requires ubuntu 14.04 (Trusty)
sudo add-apt-repository -y ppa:opencpu/opencpu-1.5
sudo apt-get update 
sudo apt-get upgrade

#install opencpu server
sudo apt-get install -y opencpu
```

The R version is updated from 3.2.2 to 3.2.4 automatically.
Is there any way to avoid this behavior?

Thanks.

**Comment by jeroenooms** [comment]
You would need to "pin" `r-base` in apt.

**Comment by SampurnR** [comment]
I tried the above. Used the following link:
[http://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package](url)

Despite "pinning" `r-base` as directed, it has updated to `R version 3.3.0 beta (2016-03-30 r70404) -- "Supposedly Educational"`.
Also, now opencpu won't install.

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opencpu : Depends: opencpu-server (= 1.3.3-trusty0) but 1.5.4-trusty8 is to be installed
           Depends: opencpu-cache (= 1.3.3-trusty0) but 1.5.4-trusty8 is to be installed
E: Unable to correct problems, you have held broken packages.
`

I tried checking the list of held packages using this command.
`apt-mark showhold`
It returned nothing (implying no packages are currently held).

Thanks.

**Comment by jeroenooms** [comment]
Try `apt-get dist-upgrade`  instead of `apt-get upgrade`.

**Comment by technOslerphile** [comment]
I found the best way is to move the base in /usr/lib/R/library/ to any other location and then create a symbolic link to the base library of the R you have installed earlier. This base is usually in /usr/local/lib/R/library folder. So:

`sudo ln -s /usr/local/lib/R/library/base /usr/lib/R/library/base`
