### ISSUE TITLE
Using opencpu with supervisord

### ISSUE THREAD

**Issue by sandys** [opencpu/opencpu#184]
hi - we have been using Rserve very comfortably with Supervisord.  For example take this example - https://github.com/dtenenba/bioc_docker/blob/1ebd3b858bbbd80a5c1a462b93d7a610d6e08a93/rserve_server_devel/supervisord.conf

Running Rserve as a long running server is simply a question of "R CMD Rserve <options>".  If I need to restart the server, then supervisord will issue a SIGHUP and the process will restart.

I'm having difficulty doing the same thing with opencpu. Usually, it is easy to port supervisord <-> systemd .. but what I see is that your systemd config actually calls out to a legacy style init.d script.

Can you please help in setting this up using supervisord ?

**Comment by jeroenooms** [comment]
I'm sorry I have no experience with `supervisord`. But you might not need it, all that the opencpu init script does is restart apache and enable the opencpu site.

**Comment by sandys** [comment]
@jeroenooms thanks for replying.
We run nginx actually and proxy to Rserve... and in this case opencpu. The reason all of this becomes important is when we redeploy new code, etc .. it is sometimes better to restart. Plus, if we screw up in our code.. supervisor will take care of killing the processes. 
Supervisord (and soon systemd) will become defacto.

If you dont want to support supervisord.. that's fine and ok. But can you simplify the systemd configuration with nginx ? supervisord works almost exactly like systemd.

**Comment by jeroenooms** [comment]
I'm not sure what you mean by simplifying the systemd configuration, but if you make a PR in the [opencpu-server](https://github.com/jeroenooms/opencpu-server) repo I will review it.

**Comment by sandys** [comment]
let me ask you this way.. can we run opencpu using "R CMD <something>" . For example, https://github.com/yihui/servr can be run on port 4000 using 
`Rscript -e 'servr::httd()'  -p4000`

now if this process gets a SIGHUP or SIGTERM, it will shut down. I can then proxy from nginx to port 4000. Simple. 

Can I get opencpu to work like this on a particular port ? if yes, then I can figure out the supervisord configs and send you a PR

**Comment by sandys** [comment]
one important point - right now, "library(opencpu)" spawns the server in the background. This is similar to "Rserve" in daemon mode. Note that systemd/supervisord will need the server to not fork... so Rserve is usually run in non-daemon/console mode . This bug is relevant - https://github.com/s-u/Rserve/issues/56

**Comment by jeroenooms** [comment]
Unlike `rserve` and `servr`, the recommended way to use opencpu is **not** to use some R based httpd because it is slow and can only handle one request at a time.

The opencpu-server uses the apache webserver from your linux distribution with `mod_R`. So you  don't worry about managing the httpd, because it is simply apache. So you just use the configurations and init scripts for apache to configure opencpu.

**Comment by sandys** [comment]
oh wow - this I did not have any idea about. This is pretty cool actually!

We use nginx through and through (because it is like 10X faster than apache on most workloads). 

BTW, this is the correct way to run httpd under systemd/supervisord - in a non forking mode by using `/usr/sbin/httpd -DFOREGROUND`  (http://serverfault.com/questions/614348/confused-about-dforeground-with-apache)

This is completely fine with me.. is it possible to get the config files to be able to run httpd by itself ? This supposes:
1. install opencpu using install.packages
2. install latest apache separately (with all security patches necessary). 
3. configure apache to use opencpu by manual configuration ?

this should be helpful for most people who are moving to their init managers or using systemd/supervisord.

**Comment by jeroenooms** [comment]
The opencpu server has been packaged up for both `deb` and `rpm`, which automatically installs all required R packages, directories, config files, etc. It works out of the box on debian, ubuntu, fedora, centos, etc. Users should not have to worry about init managers.

**Comment by sandys** [comment]
Hi
Sorry to bother you on this - but we are deploying to our own production
here. In such cases, lots of things become critical - for example adding a
ppa is a big issue because malicious ppa can bring in outdated openssl,etc.
This is just the nature of production deployment. Your systemd config also
launches an init daemon script rather than launch a non forking command
...which was flagged by our devops (which why I filed this request)

Since you already use Apache, this is already going be awesome... Because
Apache is well understood for most init managers. But it would be really
helpful if you had some rough explanation of how to manually configure this
with Apache. That way I can figure out the right configs for systemd and
supervisord and hopefully contribute them back.

**Comment by jeroenooms** [comment]
Which OS do you use? You don't need to use the PPA, you can just build the package from source yourself. Follow the instructions for [deb](https://github.com/jeroenooms/opencpu-server/tree/v1.6/debian#readme) or for [rpm](https://github.com/jeroenooms/opencpu-server/blob/v1.6/rpm/buildscript.sh).

I highly recommend that you first build the package and then install that, rather than manually installing all of the R packages, config files, scripts, etc.

**Comment by jeroenooms** [comment]
You can also have a look at the docker scripts: https://github.com/jeroenooms/opencpu-server/tree/v1.6/docker . Even if you do not use docker, they show how the package system gets built.

**Comment by jeroen** [comment]
OpenCPU 2.0 has been released. This version no longer has an init script, it just uses `apachectl restart`. 

There are detailed instructions on how to build `deb` and `rpm` files on the website. You can also have a look at the docker files to see how we build on various platforms.

Please open a new issue if you still experience problems.
