### ISSUE TITLE
Move user R packages after a major R version change

### ISSUE THREAD

**Issue by alexdeng** [opencpu/opencpu#187]
User packages are in different folder for R 3.2.\* and 3.3.*. After upgrading to opencpu 1.6, I need to manually move user packages to new folders as admin. Can/should this be done automatically as part of the upgrade experience?

**Comment by jeroenooms** [comment]
R does this on purpose because some packages are sensitive to the version of R and need to be recompiled. Afaik this is done on all platforms by the default R installation, not directly related to opencpu.

**Comment by alexdeng** [comment]
I understand. But even for desktop R installr package tries to do this automatically for user. 
For opencpu, when you have a large number of users, it's much easier to do the leg work to copy the packages/reinstall the package first, and then email users and ask them to check if their stuff are still working.
