### ISSUE TITLE
ggplotly does not seem to work with opencpu

### ISSUE THREAD

**Issue by kobus78** [opencpu/opencpu#201]
Plotly open-sourced their plotly.js library at the end of 2015. I installed the plotly library and then tried to use the plotly::ggplotly function to get an interactive plot in my opencpu R file but it does not render to an interactive plot on the web page. Are there any examples on how to do this?

**Comment by balexbyrd** [comment]
I've had success using htmlwidgets

`p <- plot_ly(*visual*) %>% layout(*layout*) \n htmlwidgets::saveWidget(as.widget(p), "visual.html", selfcontained = TRUE)`

Given you're using ggplot, you may have to convert using p <-ggplotly(*your ggplot object*)

Then if you're trying to integrated it into a webpage, you can use the session.loc+ 'files/visual.html' in an iframe

**Comment by jeroen** [comment]
The [leafletapp](https://github.com/rwebapps/leafletapp) is an example of an app using htmlwidgets.
