### ISSUE TITLE
build on Debian: dependencies not available?

### ISSUE THREAD

**Issue by nicholaelaw** [opencpu/opencpu#203]
I'm building opencpu on debian 8.6. Following instructions written [here](https://github.com/jeroenooms/opencpu-server/tree/master/debian#readme).

I get this warning from `buildpackages.R`:

```
# Builds the library with R packages.
Rscript` ./opencpu-lib/buildpackages.R
Building with AppArmor support
Warning: dependencies ‘R.rsp’, ‘methods’, ‘utils’, ‘tools’, ‘stats’, ‘parallel’, ‘hms’, ‘grDevices’, ‘graphics’ are not available
also installing the dependencies ‘stringi’, ‘magrittr’, ‘assertthat’, ‘lazyeval’, ‘stringr’, ‘Rcpp’, ‘digest’, ‘formatR’, ‘highr’, ‘markdown’, ‘yaml’, ‘memoise’, ‘whisker’, ‘rstudioapi’, ‘git2r’, ‘withr’, ‘mime’, ‘curl’, ‘R6’, ‘tibble’, ‘base64enc’, ‘evaluate’, ‘httpuv’, ‘knitr’, ‘jsonlite’, ‘devtools’, ‘httr’, ‘protolite’, ‘brew’, ‘openssl’, ‘RAppArmor’, ‘feather’, ‘sendmailR’, ‘pander’
```

which does not seem right to me. These packages are clearly available, from either base R or from CRAN. However the building process continues and finishes without error. Is this behaviour normal? Or, how do I fix the dependencies?

**Comment by jeroenooms** [comment]
Is `libicu-dev` installed on the system?

**Comment by nicholaelaw** [comment]
Yes it is. `apt` says I've got the latest version installed.

**Comment by nicholaelaw** [comment]
OK I think I've solved it. Remove this line 

    environment(.libPaths)$.lib.loc = character(0)

from `./opencpu-lib/buildpackages.R`. Then manually add `hms`, `R.rsp`, `R.cache`, `R.oo`, `R.utils`, `R.methodsS3` source to the same directory. Now it builds without any dependency warnings.

**Comment by jeroenooms** [comment]
Well that should not be needed. Can you show me the full build log? It should look like e.g. this: https://launchpadlibrarian.net/286503454/buildlog_ubuntu-xenial-amd64.opencpu_1.6.5-xenial3_BUILDING.txt.gz

**Comment by nicholaelaw** [comment]
Ehh...how do you grab the full build log again? Pipe it to a text file? Or is there a switch to do that?

**Comment by jeroen** [comment]
Is this problem solved? The build scripts were refactored for OpenCPU 2.0.
