### ISSUE TITLE
predict function not working with opencpu

### ISSUE THREAD

**Issue by vibhas2511** [opencpu/opencpu#205]
Hello, 

The segmented::predict returns predictions and optionally associated quantities from a fitted segmented model object. 

In opencpu, the predict function isn't able to read the model object (U1.temperature not found)

![ocpu-issue-1](https://cloud.githubusercontent.com/assets/20641789/19796189/1ff7bd00-9d00-11e6-9386-e4efb1a763a3.png).

However, the model object does have U1.temperature as shown in the image below (this image is from the console output of opencpu when returning the coefficients of the model).

![ocpu-2](https://cloud.githubusercontent.com/assets/20641789/19796608/3ef5b330-9d03-11e6-8052-eb8dc86ed808.png)

The line of code in the R script is as follows:

predictedVals <- segmented::predict(cacheModel, newdata = data.frame(temperature = df1$temperature))

where cacheModel is the model object where one of the coefficients is indeed U1.temperature.

Can you please help with using the predict function with opencpu.

Thanks.

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
