### ISSUE TITLE
Web page not showing up

### ISSUE THREAD

**Issue by leegabriel** [opencpu/opencpu#209]
Hi there, 

I'm on Ubuntu 14.04 and followed the instructions exactly in the server manual. I can access the rstudio web interface via http://my-ip-address:8787 (as expected by looking at rstudio.conf) but I cannot accomplish the same thing for opencpu by going to http://my-ip-address:8004 (which is the port written in opencpu.conf). Furthermore, the /rstudio and /ocpu paths don't appear to be working, even though the conf files make it look like they should(?).  Any guidance here would be greatly appreciated!

**Comment by jeroen** [comment]
Are you sure the `opencpu.conf` site is enabled in Apache? If this problem still exists in opencpu 2.0, please open a new issue with more details on how you installed the server. It works out of the box for most users.
