### ISSUE TITLE
How to edit .opencpu.conf when using JS Client only. 

### ISSUE THREAD

**Issue by chjuruena** [opencpu/opencpu#210]
I'm having this error:
`Server error: R call did not return within 90 seconds. Terminating process. In call: NULL `
when I call     "ocpu.rpc("identity", ...". I can normally receive the result in my other function but the error surfaces in an another function with almost the same R script code. 
I've read in another issue [https://github.com/jeroenooms/opencpu/issues/78](url) that editing the timeout in .opencpu.conf can remove this error or this solution [https://github.com/jeroenooms/opencpu/issues/131](url). However, I only run using the JS client. I tried editing the .opencpu.conf but it does not reflect since the error still persists.  Is there a way I can edit the timeout even if i'm just using the JS lib? I am not running anything form the terminal. Just plainly opening the web page that I am using with opencpu js script. Sorry for the very noob question. I am just a beginner in web programming. Thank you for answering!

**Comment by jeroen** [comment]
Only the server admin can raise the timeout. You can't do this in the client.
