### ISSUE TITLE
session namespace

### ISSUE THREAD

**Issue by baba-beda** [opencpu/opencpu#212]
Hi, my question is: how can I pass as an argument to function not entire session but one object from ocpu/tmp/sessionkey/R/ endpoint? I use opencpu with javaScript. So usually for chain calls I just pass session, but now I need one specific object from it.
Thank you in advance,
Daria

**Comment by jeroenooms** [comment]
Can you try `session::object` notation?

**Comment by baba-beda** [comment]
I understand how to use it in test requests with curl, it's pretty easy. But when I use chain requests in javascript, I need to pass Session-object, not String. Am I wrong?

**Comment by jeroen** [comment]
Did you figure this out? You can use `new Snippet("session_id::object_name")` to pass literal code in the javascript client.

If this doesn't work, please open an issue in [opencpu.js](https://github.com/opencpu/opencpu.js) repo.
