### ISSUE TITLE
loading of rJava in opencpu cloud server failed..

### ISSUE THREAD

**Issue by manojasati** [opencpu/opencpu#214]
I am using a package that depends on rJava and when i used to work with it from R console it use to work fine bu t when i am invoking a function using ocpu.rpc(..) in opencpu cloud server i get following error message...
.onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/../R/x86_64-pc-linux-gnu-library/3.3/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory

Any help will be appreciated...

**Comment by jeroen** [comment]
It says `rJava` cannot be loaded because `libjvm.so` is not found. You need to install `java` or `openjdk` for your system. This is not related to opencpu.

**Comment by TianrenWang** [comment]
@jeroen I installed Java JDK 12 and I still get the same message. Why is this designed to need the client to install Java anyways, why not just handle this on the server side?
