### ISSUE TITLE
OpenCPU shows different version of R in info object

### ISSUE THREAD

**Issue by technOslerphile** [opencpu/opencpu#222]
Hi, I have the latest OpenCPU installed which comes with R 3.3.3. I do have R 3.3.1 compiled from source which was already installed before OpenCPU and want to use this 3.3.1 version for OpenCPU as well. I created a symbolic link in /usr/lib/R/library/ folder for the packages base, stats, utils, compiler and tools to point to the 3.3.1 versions in /usr/local/lib/R/library folder. That is, when I check for base by:

> `https://myhostname.com/ocpu/library/base `
It shows the base R as 3.3.1. Same goes with utils, stats, tools and compiler too. However, when I try to do any operation, (for example, qplot from ggplot2 for plotting some data points), the info shows it as R version 3.3.3.  Same is the case when I use some function from the default packages as well (for example, read.csv from utils). 

X-ocpu-r: R version 3.3.3 (2017-03-06)

But 

> `https://myhostname.com/ocpu/library/base`

 shows 3.3.1

**Comment by jeroen** [comment]
This is a bug in your installation. You really shouldn't mix and match base libraries from different R versions. What OpenCPU tells you must be correct: you are running a different version of R than the base library.

**Comment by technOslerphile** [comment]
This is not a bug with the installation. In many cases, you may want to use the same R version installed in your machine to be used with OpenCPU. I think this is rather due to the fact that there isn't a seamless integrate the already existing R with OpenCPU.
