### ISSUE TITLE
Link to opencpu-server.pdf is broken 

### ISSUE THREAD

**Issue by Dekker1967** [opencpu/opencpu#223]
The OpenCPU has broken links to the server manual:
On page "Open CPU API Explorer" the Link "PDF Manual" in header is broken.
On page "Download" the link to "Server Manual PDF" is broken as well.

Broken link: https://jeroenooms.github.com/opencpu-manual/opencpu-server.pdf
This one worked - showed version 1.5 of the server manual: https://jeroen.github.io/opencpu-manual/opencpu-server.pdf

**Comment by jeroen** [comment]
Fixed @ https://github.com/opencpu/opencpu/commit/86960ea2aa615577bf8bdc18a32e74dad552e6f6. Thank you for reporting!
