### ISSUE TITLE
IP address restrictions for opencpu server

### ISSUE THREAD

**Issue by frankyan** [opencpu/opencpu#230]
Is it possible to restrict the ip addresses access to the opencpu server? Or only allow localhost access?

**Comment by jeroen** [comment]
Yes, `opencpu-server` simply uses Apache2 so you can use all apache2 settings. For example you can add:

```
	<Location />
		# This assumes Apache 2.4
		Require 123.123.123.123
	</Location>
```

**Comment by frankyan** [comment]
Thanks. It works!
