### ISSUE TITLE
Tag opencpu-server docker images

### ISSUE THREAD

**Issue by mtricht** [opencpu/opencpu#246]
None of the images on dockerhub have a tag, the only available tag is "latest".

For example we use https://hub.docker.com/r/opencpu/base/
An older version of the image works for us but a newer version does not. If there were tags we'd be able to lock the version, which we sadly can't atm.

**Comment by jeroen** [comment]
Thanks that's useful feedback. I'll start tagging images for next releases.

**Comment by swordbeta** [comment]
@jeroen Great!

Just to give you and others an idea why our stuff stopped working; the base image has been updated to ubuntu 16.04 from 14.04. We rely on a few R packages that we install through our Dockerfile such as chron, cooptrees, curl and more. These packages rely on libraries that were in the 14.04 image but not in the 16.04 such as curl, gcc, g++ and more.

**Comment by jeroen** [comment]
Right, the base image is a bit lighter now. But you can easily `apt-get install` those yourself if you need them, right?

**Comment by swordbeta** [comment]
@jeroen Yes! Just had to figure out what changed :)

**Comment by jtrees** [comment]
Any chance of getting another tag?

**Comment by Mike-Gibson** [comment]
We are also hoping to get a non-latest tag on the base docker image, as we need to be sure of the version we are building on. Any chance of a tag please?

**Comment by fabianmoronzirfas** [comment]
Yes pretty please tag the containers.

**Comment by jeroen** [comment]
I can tag them, but they have the ppa enabled by default, so the first time you would run `apt-get upgrade` it would still update all packages including opencpu... 

Would that really be useful?

**Comment by Mike-Gibson** [comment]
It would still be useful to us to have the images tagged. We would be using the base image and running `apt-get update` and then installing specific packages we need on top of the base image. I don't believe this would cause the installed version of open CPU to be upgraded, so we could then be confident of the version of open CPU in our final built docker image, regardless of whether a new version had been pushed to the ppa. Hopefully I've explained it clearly enough? Happy to elaborate if it helps.
