### ISSUE TITLE
perfomance degradation even with empty func for paralel req's

### ISSUE THREAD

**Issue by sensorua** [opencpu/opencpu#248]
Hi! 
I did some simple "benchmark" for OpenCpu 2.0.3
Prereqests: Ubuntu 16.04.2 LTS, CPU 2 cores Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz and just 4 GB memory. Machine located in local network. OpenCPU installed by standart instruction from https://www.opencpu.org/download.html.

At first - i created package (perftest) without any dependencies and with one function:
`hello <- function() {
  return(1);
}
`
So, as you can see, it does nothing.
After that installed package, add it to preload section of server.conf and restart apache.
So - lets test! Nothing special, just calling service POST http://10.0.12.166/ocpu/library/perftest/R/hello/json with Fiddler (http://www.telerik.com/fiddler)

Results (paralel req count/ medium latency for req/ all time for batch):
1 req / 200 ms / 200 ms
2 req / 220 ms / 239 ms
4 req / 400 ms / 426 ms
8 req / 850-1000 ms / 1309 ms
16 req / -- / 6878 ms

What we have here:
1. Is it OK about overhead of preloaded package with empty function with 200 ms (for 1 req)?
2. Any ideas about so fast growing latency with paralel requests?

It's interesting to look to requests timeline: https://image.prntscr.com/image/AM6Qg6X3Qb6ZrnPQ-G_SDA.png
You can see here - that first "group" started and finished at the same time - what resource they are waiting for?

**Comment by jeroen** [comment]
Thanks for the results. Can you maybe explain how you perform these requests? It it running on localhost or a remote? Does your client recycle the https connection, or if they get multiplexed.

It would be great if I could easily reproduce these results so we can compare different setups, and I can perhaps try to optimize things here and there.

The overhead of a single request is usually between 100ms and 200ms, depending on the hardware. I don't think that it is waiting for any resource, it's just R doing stuff. But perhaps there is something that is blocking rApache, I'll look into this.

Obviously, if your machine has two cores, and the server is running more than two concurrent R sessions, things start slowing down proportionally. It sounds like you assume apache is just waiting for something, what is happening is that R is actually using 100% cpu for those 200ms.

I plan to do another round if performance investigation and optimization for the next release.

**Comment by jeroen** [comment]
OK so I found that 80ms is now lost in evaluate: https://github.com/hadley/evaluate/issues/79. That is probably something I can improve on.

**Comment by jeroen** [comment]
Hi @sensorua, I have done two significant performance tweaks. Could you update to the latest 2.0.3 build and rerun your checks?

**Comment by sensorua** [comment]
Hi @jeroen!
Does all of this changes already in ubuntu repository (so it;s only apt-get upgrade requred) - or i need re-install opencpu from sources?

**Comment by sensorua** [comment]
Ooo yes! Just installed opencpu 2.0.3.1 version - it's much faster!
Single requests always around 100 ms, parallel requests (remote server in intranet, no https, no client-connection reuse) have been processed in much optimal way
req count / med. latency per req / batch time
4 req / 180-200 ms / 202 ms
8 req / 380-400 ms / 456 ms
16 req / 600-700 ms / 919 ms

About reproducible results - i just use free Windows tool https://www.telerik.com/download/fiddler, unfortunatly, it's not really load test stuff, just HTTP proxy/client/debugger - but it's enough for simple tests
If you need - i can do prepare some small instruction for it

**Comment by jeroen** [comment]
If you use ubuntu, just `apt-get update` should get you the updates.

**Comment by jeroen** [comment]
Glad it's faster now, I'll try to write some R code to do concurrency performance testing.
