### ISSUE TITLE
argument check?

### ISSUE THREAD

**Issue by feng5** [opencpu/opencpu#250]
```
> curl https://rwebapps.ocpu.io/appdemo/R/hello/json -d "myname=-q"
invalid argument to unary operator

In call:
-q
```

how can i check if the argument that user posted is legal？

**Comment by jeroen** [comment]
One way would be to just pass json data, then you can simply validate the JSON.

**Comment by jeroen** [comment]
If you post data arguments such as JSON or primitives you can validate on the client. If you post R syntax there is no way to validate this, other than actually trying to parse it.
