### ISSUE TITLE
ERROR: [on_request_read] connection reset by peer

### ISSUE THREAD

**Issue by katezelaya** [opencpu/opencpu#253]
![screen shot 2017-07-07 at 10 36 46 am](https://user-images.githubusercontent.com/9877871/27962541-3a174e0a-6300-11e7-8eb7-766f9a207111.png)

![screen shot 2017-07-07 at 10 32 10 am](https://user-images.githubusercontent.com/9877871/27962327-94ac3f0c-62ff-11e7-851d-1dfe455aeed3.png)

**Comment by jeroen** [comment]
Note that if you have the cloud server installed, you don't need to start the server in R. You should just be able to access `http://localhost/ocpu/` on your server. Can you test this?

**Comment by katezelaya** [comment]
![screen shot 2017-07-07 at 12 45 23 pm](https://user-images.githubusercontent.com/9877871/27967985-31b88fc2-6313-11e7-8f66-567018be5a86.png)
It works :)

![screen shot 2017-07-07 at 12 47 55 pm](https://user-images.githubusercontent.com/9877871/27967981-2d3ee3ba-6313-11e7-981d-ab60a6f65cf7.png)
However, I have a question about this screenshot. How come I cannot see the appdemo directory in my terminal but can access it on the browser? Lets say I wanted to modify the appdemo html, how can I access it?

And how is it on the browser if I never loaded it into the server?

**Comment by jeroen** [comment]
Yes, to make a package available on the cloud server you need to install it in one of the global libs, either as user `root` or as user `opencpu`. 

If you install with `install.packages()` or `devtools::install_github()` the library will become available under `http://localhost/ocpu/library/<pkg>/`. 

If you install via `opencpu::install_apps()` it will be at `http://localhost/ocpu/apps/<user>/<pkg>/`
