### ISSUE TITLE
Is it possible to run tensorflow inside ocpu.io?

### ISSUE THREAD

**Issue by jtrecenti** [opencpu/opencpu#254]
I'm trying to use `keras` R package to run a model at ocpu.io and for that I would need tensorflow running. This is the result after running `tensorflow::tf_config()`:

```
> httr::GET('https://cloud.opencpu.org/ocpu/tmp/x05575a9ecd/stdout')
Response [https://cloud.opencpu.org/ocpu/tmp/x05575a9ecd/stdout/text]
  Date: 2017-07-15 14:19
  Status: 200
  Content-Type: text/plain; charset=utf-8
  Size: 205 B
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /usr/bin/python2.7
 /usr/bin/python3.5
```

However, when I run `tensorflow::install_tensorflow()`, I get this result

```
Prerequisites for installing TensorFlow not available.

Execute the following at a terminal to install the prerequisites:

$ sudo apt-get install python-pip python-virtualenv
```

and I think I cannot run these thing without help :)

**Comment by jeroen** [comment]
I've tried to install tensorflow on the server. Could you try again?

**Comment by jtrecenti** [comment]
```
TensorFlow v1.2.1 (/usr/local/lib/python2.7/dist-packages/tensorflow)
Python v2.7 (/usr/bin/python)
```

thanks!

**Comment by jtrecenti** [comment]
Sorry to reopen this issue.

Now my OpenCPU CI is giving this error:

```
call: keras::load_model_hdf5(file_path)
error: The h5py Python package is required to save and load models
```

I think that it is necessary to run (maybe with `sudo`)

```
pip install h5py
```

and then I think the code below will return true:

```
httr::POST('https://cran.ocpu.io/reticulate/R/py_module_available/json', body = list(module = 'h5py'))
```

**Comment by jeroen** [comment]
OK can you try again?
We probably need a better solution for python dependencies.

**Comment by jtrecenti** [comment]
It is working! thanks.

**Comment by jeroen** [comment]
Did you get everything to work? If you want we can do a short guest blow post showcasing your app.

**Comment by jtrecenti** [comment]
I've sent an e-mail to you!
