### ISSUE TITLE
OpenCPU returns "embedded nul in string" in call base::rawToChar(x) for compressed requests

### ISSUE THREAD

**Issue by vinodhkanna** [opencpu/opencpu#262]
I have deployed few custom packages and i am able to send requests and retrieve responses. Since my request data is large, i have tried sending the JSON data with Content-Encoding: gzip. In this scenario, i receive the following error:

239
embedded nul in string: '\037\x8b\b\0\0\0\0\0\0\0u\xd0\xcd\016\xc2 \f\0\xe0w\xe9\031\033~\n\023^\xc5xp[\\\026]\xdc\xe2\xdfa\xe1\xdd-\x8e%Æ°\v4\xf4\xa3-\xccP\xf7\xed\035\xc2a\x86\021\xc2\xce;\x89F\xc0\004A\xa2\024P_/\020\024\xef\xbcF\xb1\020NØ¢\xd0Yh\x8f\xe4\x8a\xc2da\bmU\024\x94\x85Uh\xcb5l\026N\xa1\xa7\xa2pY(\xaf\xb7F\xad\xd6Q\xad\xde\xea\xb3_\xab\030"$]4\xfe\xc7\020.\x86\xaa\xff\x8f\x93\xf1(`h:\b3\xb4Ï¾\x85\0\xf5[*X\xf8\xb7\xe6Ð¤\027\xe5pJw8\x8e\002\xba1]Z\x8b\x9d^9\xc3\xe19M\xc3\035\x9b\xdb\xfd\xc1\xa7\x96y\xfc\0/\x81\021%\xcc\001'

In call:
base::rawToChar(x)

Without request compression, the invocation succeeds. I searched through the issues and documentation and couldn't find any resource that explains this. Our API takes request as JSON and serializes response as JSON (headers below)

**Request headers**
POST /ocpu/library/elvacs2/R/reward/json?pretty=FALSE&auto_unbox=TRUE HTTP/1.1
Accept: application/json
Content-Type: application/json
Content-Encoding: gzip
User-Agent: Java/1.8.0_111
Host: 172.24.104.153:80
Connection: keep-alive
Transfer-Encoding: chunked

**Response Headers**
HTTP/1.1 400 Bad Request
Date: Fri, 06 Oct 2017 13:23:42 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, X-ocpu-session, Content-Type, Cache-Control
Access-Control-Allow-Headers: Origin, Content-Type, Accept, Accept-Encoding, Cache-Control, Authorization
Access-Control-Allow-Credentials: true
X-ocpu-r: R version 3.4.1 (2017-06-30)
X-ocpu-locale: en_US.UTF-8
X-ocpu-time: 2017-10-06 18:53:42 IST
X-ocpu-version: 2.0.4
X-ocpu-server: rApache
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

**Comment by jeroen** [comment]
Thank you. It is a little unusual to gzip your POST in http, because usually the other party first needs to advertise with an `Accept-Encoding` header that it supports gzip in the first place.

I **think** you can get this to work by editing `/etc/apache2/sites-enabled/opencpu.conf` on your server. There is a line there that states `SetOutputFilter DEFLATE`. Underneath that create a new line with:

```
SetInputFilter DEFLATE
```

Then save and run `sudo apachectl restart`. Let me know if this works, I might enable it by default :)

**Comment by vinodhkanna** [comment]
I tried compressed request with rnorm as well and i receive the similar error. Does OpenCPU supports compressed requests? I tried requesting for compressed response (Accept-Encoding: gzip) and it works fine.

**Curl Request**
_curl -v -i http://localhost/ocpu/library/stats/R/rnorm/json -H 'Content-Encoding:gzip' -H 'Content-Type:application/json' --data-binary @test.gz_

Uncompressed data : {"n":3, "mean": 10, "sd":10}

**Response**
_<
embedded nul in string: '\037\x8b\b\0BQ\xd7Y\0\003\xabγ2\xd6Q\xc8MM̳R04\xd0Q(N\xb124\xa8\xe5\002\0PQ\xffL\027'

In call:
* Closing connection 0_

**Comment by vinodhkanna** [comment]
Works GREAT. Thank you @jeroen. I should have been more diligent and looked into the apache configuration knowing this never reached my R package. Thanks Again and i sincerely hope this can be made default in the upcoming releases.

**Comment by jeroen** [comment]
OK let me know if you find any side effects. Otherwise I'll make it the default.

**Comment by vinodhkanna** [comment]
We have four R APIs that consume large amount of data with different structures, i have tested them with Content-Encoding: gzip and without gzip. Both options work fine. I did a test with Content-Encoding: deflate and the issue remains. But this isn't a issue for me though. 

THANKS for your support and extensive documentation of API which makes it easier for us to integrate with OpenCPU APIs with very less learning curve.
