### ISSUE TITLE
opencpu 1.6 and preload

### ISSUE THREAD

**Issue by swestrop** [opencpu/opencpu#263]
When we preload ggplot2 in the preload section of the config file, then other functions do not work any longer.

Examples:

```
package or namespace load failed for 'officer' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'Rcpp' 0.12.9 is already loaded, but >= 0.12.12 is required

package or namespace load failed for 'dplyr' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'tibble' 1.2 is already loaded, but >= 1.3.1 is required
```

It only occurs when preload is filled.

As you can see in the SessionInfo, wrong versions of e.g. tibble are loaded via namespace. We have the newest version on our system and all our functions work when preload is empty.

Any help is really appreciated, so that we can use preload and have new versions of all packages loaded via namespace.

SessionInfo:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8    LC_NUMERIC=C            LC_TIME=en_US.UTF-8    
 [4] LC_COLLATE=en_US.UTF-8  LC_MONETARY=en_US.UTF-8 LC_MESSAGES=C          
 [7] LC_PAPER=C              LC_NAME=C               LC_ADDRESS=C           
[10] LC_TELEPHONE=C          LC_MEASUREMENT=C        LC_IDENTIFICATION=C    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] evaluation360_0.1 opencpu_1.6.7    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9      assertthat_0.1   plyr_1.8.4       grid_3.4.2      
 [5] jsonlite_1.3     gtable_0.2.0     magrittr_1.5     RAppArmor_2.0.2 
 [9] evaluate_0.10    scales_0.5.0     ggplot2_2.2.1    stringi_1.1.2   
[13] lazyeval_0.2.0   unixtools_0.1-1  tools_3.4.2      stringr_1.2.0   
[17] munsell_0.4.3    parallel_3.4.2   sendmailR_1.2-1  compiler_3.4.2  
[21] colorspace_1.3-2 base64enc_0.1-3  openssl_0.9.6    tibble_1.2  
```

**Comment by swestrop** [comment]
Thanks for your response!

Yes, it's a cloud server on linux Ubuntu 14.04.5 LTS. Output is the same as I posted in sessionInfo() above.

Unfortunality there is no chance for us to upgrade to 2.0 soon.

Is it possible for us to update the opencpu packages so it works with latest R 3.4.2? Or is it possible that we can prevent the older packages (shipped with opencpu 1.6.7) from loading?

**Comment by jeroen** [comment]
You can add custom preload scripts to the `/etc/opencpu/Rprofile` file. That file gets sourced before opencpu is loaded. So just edit this file and add some lines like:

```r
library("ggplot2")
library("whatever")
```

You could also be explicity and set which library you want to load ggplot2 from e.g.:

```r
library("ggplot2", lib.loc = "/usr/local/lib/R/site-library")
```

Hope this helps.

**Comment by swestrop** [comment]
This helps a lot, thank you very much!

**Comment by jeroen** [comment]
Ok great good luck!

**Comment by LearningRaph** [comment]
Hi,
I'm having the same problem with openCPU release 2.2.2. And as this is currently the last, I can't update as recommended...

```R
package or namespace load failed for 'xyz' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'lifecycle' 0.2.0 is already loaded, but >= 1.0.0 is required
```

Thanks for your input !

**Comment by jeroen** [comment]
Are you using the latest build? I updated to lifecycle 1.0.0 about a month ago.

**Comment by LearningRaph** [comment]
yeah I updated it and it works again. I wanted to use a fixed version (2.2.2) in my docker file to avoid new problems in the future.... so the solution caused the problem ^^

**Comment by jeroen** [comment]
I created a new tag `2.2.2-1` which is an alias of the current latest.

**Comment by LearningRaph** [comment]
oh thanks @jeroen :)

**Comment by stefvanbuuren** [comment]
See also #327.
