### ISSUE TITLE
Webhook for private Github repo doesn't work

### ISSUE THREAD

**Issue by claytonmarinho** [opencpu/opencpu#266]
I setup an OpenCPU server (running in a container) and tried to deploy some R repos from GitHub using webhooks. That works nicely when repo is public, but when private I've got this response: `Failed to read https://raw.githubusercontent.com/user/repo/master/DESCRIPTION. Repsitory does not contain a proper R package`.

That url must have a `token` when private, but how to fix it on server?

Attempts: 

 - auth_token in the Payload URL: https://ocpu.domain.com/ocpu/webhook?sendmail=false&auth_token=xxxxxxxxxxxxxxxxxxxxxxx
 - auth_token in /etc/opencpu/secret.conf
 - GITHUB_PAT in .Renviron file 
 - GITHUB_PAT in /etc/opencpu/Renviron
 - SSH key
 
Cheers.

**Comment by jeroen** [comment]
Fixed via: https://github.com/opencpu/opencpu/commit/882dcd0f015b1b41831c0f87507123e67f9f68ab

**Comment by jeroen** [comment]
Hmm still doesn't work. AppArmor is overly protective:
```
Oct 28 14:19:08 dev kernel: [2481921.519471] audit: type=1400 audit(1509200348.162:247): apparmor="DENIED" operation="open" profile="opencpu-exec" name="/etc/opencpu/secret.conf" pid=9677 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0
```

**Comment by jeroen** [comment]
OK I think this is fixed now. Can you try to install the devel version on your server?

```
git clone https://github.com/opencpu/opencpu
sudo R CMD INSTALL opencpu --library=/usr/lib/opencpu/library
sudo apachectl restart
```

**Comment by jeroen** [comment]
I think it's fixed now. Can you check if this is solved in the 2.0.6 release?

**Comment by claytonmarinho** [comment]
Hi @jeroen.
Works like a charm in the v2.0.6 with the auth_token param.
Example: https://ocpu.domain.com/ocpu/webhook?sendmail=false&auth_token="xxxxxxx"
Thank you.

**Comment by jeroen** [comment]
It should also work if you set it in `/etc/opencpu/secret.conf` or defined `GITHUB_PAT` in `/etc/opencpu/Renviron`.

**Comment by TianrenWang** [comment]
I had the exact same error in the latest version (2.1.2). `Failed to read https://raw.githubusercontent.com/bhklab/DNF2/master/DESCRIPTION. Repsitory does not contain a proper R package.`

This error only occurs when I set the repository to private. If it is public there is no problem.

**Comment by jeroen** [comment]
@TianrenWang did you try the above solutions? You need to set a PAT on your server if you want it to authenticate with private repositories.

**Comment by TianrenWang** [comment]
@jeroen 
![image](https://user-images.githubusercontent.com/23157077/60344438-8d7ca600-9984-11e9-9ad3-5fc94da43a79.png)
I added an authentication parameter on the webhook URL setting on the repository while the repo was private. I still got the same error.
