### ISSUE TITLE
Question - multiple requests at a time?

### ISSUE THREAD

**Issue by lautiamkok** [opencpu/opencpu#267]
I just have a question on opencpu - does it serve multiple requests at a time?

We have been using Shiny open source version for a few years but the [problem with it is that it only server one request at a time](https://www.r-bloggers.com/shiny-server-open-source-edition-solution-for-cpu-bound-apps/):

> if one user is doing some calculation, the other user must wait until that process finished!

It seems that it has the same limitation with [jug](https://github.com/Bart6114/jug) too. Hence it has a plugin on top called [jug.parallel](https://github.com/Bart6114/jug.parallel).

What about opencpu then?

**Comment by jeroen** [comment]
Yes the `opencpu-server` stack is a native apache stack and can handle hundreds of concurrent requests.
