### ISSUE TITLE
Getting data in Browser

### ISSUE THREAD

**Issue by abhik1368** [opencpu/opencpu#273]
I studied opencpu and tried a lot to use the results over browser but i couldn't . 
I use curl in command line to get the output 
curl http://10.239.12.18:8200/ocpu/library/meanr/R/meanr/json -d n=40

Is their anyway to retrieve the results over browser without using curl

I tried this it didn't work
http://10.239.12.18:8200/ocpu/library/meanr/R/meanr/json?n=40

**Comment by jeroen** [comment]
You should use the [javascript client](https://www.opencpu.org/jslib.html).
