### ISSUE TITLE
service timeout

### ISSUE THREAD

**Issue by keshav-valgen** [opencpu/opencpu#276]
When I add rforcecom package in my new r package it's giving service time out error in webhooks. If i removed rforcecom from description page in my r package I won't get any error in webhooks. Anyone can help me in this

**Comment by jeroen** [comment]
If the package installation (including dependencies) takes longer than 30seconds, Github may report a service timeout. However the installation actually continues. You should receive an email if the installation was successful.

**Comment by keshav-valgen** [comment]
I got a mail that RForcecom installed successfully but still in webhooks showing service timeout error

**Comment by jeroen** [comment]
You can ignore the github timeout message. Github doesn't like to wait for more than 30 seconds but the installation takes longer. What matters is the email confirmation.
