### ISSUE TITLE
Can't update package

### ISSUE THREAD

**Issue by kostapanfilov** [opencpu/opencpu#277]
I have package in private github repo
So, I've updated it and tried to run it in ocpu

But there are no changes.
I think, I need to restart ocpu, but 'sudo apachect1 restart' doesn't solve my problem

**Comment by jeroen** [comment]
Try to bump the pkg version number and check in `/ocpu/library/yourpkg/info` if it has been installed. Restarting apache is only needed if your package is preloaded. Sometimes the browser caches info, press CTRL+R in the browser to force a refresh.

**Comment by kostapanfilov** [comment]
yes, it was cache.... thank you!
