### ISSUE TITLE
How I get the session name?

### ISSUE THREAD

**Issue by xishi00** [opencpu/opencpu#279]
When I perform a post request, how I get the session name?
I want to run a script file and get the output file, so I need knowing the session name. Is there any way  to directly get the output pdf file through a request like:
curl https://cloud.opencpu.org/ocpu/library/knitr/examples/knitr-minimal.Rmd -d "format=docx"
or 
curl https://cloud.opencpu.org/ocpu/library/knitr/examples/knitr-minimal.Rnw

**Comment by jeroen** [comment]
The session ID is contained in the `x-ocpu-session` response header. The full location of the session is contained in the `location` response header. Try running curl with `-v` and look at the response headers:

```
curl https://cloud.opencpu.org/ocpu/library/knitr/examples/knitr-minimal.Rmd -d "format=docx" -v
```
