### ISSUE TITLE
Please provide more detailed install-from-source instructions

### ISSUE THREAD

**Issue by kortschak** [opencpu/opencpu#281]
I have an [issue in github.com/kortschak/arrgh](https://github.com/kortschak/arrgh/issues/9) asking for more detailed dependency installation instructions for opencpu, but it seems to me that this really belongs here where it will be kept up-to-date.

Can you add an install-from-source instruction for opencpu somewhere, including the necessary underlying dependencies (in the absence of a CRAN doc, I can't easily find what the system and package deps are).

**Comment by kortschak** [comment]
My use is probably fixed by having found the CRAN page and the list of deps, but this would still be nice to have.

**Comment by jeroen** [comment]
Did you find https://github.com/opencpu/opencpu-server/blob/master/debian/readme.md ?

**Comment by jeroen** [comment]
And for rpm: https://github.com/opencpu/opencpu-server/blob/master/rpm/readme.md

**Comment by kortschak** [comment]
> Did you find https://github.com/opencpu/opencpu-server/blob/master/debian/readme.md ?

That's perfect. Thanks.
