### ISSUE TITLE
delay after updating git repo when serving locally

### ISSUE THREAD

**Issue by greymonroe** [opencpu/opencpu#284]
I am working in Rstudio and learning to use opencpu, so please bear with me. When I push an update to my R package on github and then run...

ocpu_start_app("{user}/{repo}")

The site that is served is not the updated version. When I checked things with

ocpu_start_server()
GET ../apps/{user}/{app}

I noticed that the x-ocpu-time for this is well behind the current time.  I did some troubleshooting noticed that it only updates the app every 15 minutes. Not sure that this is technical issue, but it is definitely inconvenient for learning/developing.  What is the best way for me to push my code to github and see an updated version without waiting?

Thank you!

**Comment by jeroen** [comment]
Probably browser cache. Try pressing ctrl+R in your browser to force a refresh.

**Comment by greymonroe** [comment]
Thank you, yes cmd+shift+R worked
