### ISSUE TITLE
OPTIONS method returns "401 unauthorized" when HTTP Basic Auth is enabled

### ISSUE THREAD

**Issue by elielw** [opencpu/opencpu#285]
When browser performs a preflight request I keep getting 401 unauthorized. I tried rewriting the OPTIONS method in the 'opencpu.conf' file, but it doesn't work.

This is my opencpu.conf file

        <Location /ocpu>
                SetHandler r-handler
                RHandler opencpu:::rapachehandler
                SetOutputFilter DEFLATE

                AuthType Basic
                AuthName "Restricted Content"
                AuthUserFile /etc/apache2/.htpasswd
                Require valid-user

                RewriteEngine On
                RewriteCond %{REQUEST_METHOD} OPTIONS
                RewriteRule ^(.*)$ $1 [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]]
                Header always set Access-Control-Allow-Credentials "true"
                Header always set Access-Control-Max-Age "1000"
                Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security$
                Header always set Access-Control-Allow-Origin "*"
                Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
        </Location>

Any clues on how to make this work?

**Comment by elielw** [comment]
As usual, 5 minutes after I ask the question I find a solution. The "<LimitExcept OPTIONS>" tag seems to solve the problem. Although I'm still dealing with CORS issues.

    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile /etc/apache2/.htpasswd
    <LimitExcept OPTIONS>
         Require valid-user
    </LimitExcept>

**Comment by jeroen** [comment]
There is actually an option [in opencpu itself](https://github.com/opencpu/opencpu/blob/740134202dc666a0c4b7b6c25f1ed8fc107d3386/R/request.R#L57-L63) to set the CORS headers. Did that not work for you?

**Comment by elielw** [comment]
The CORS issue was solved, but out of curiosity where can I set this option?

**Comment by jeroen** [comment]
It's enabled by default but you can change it in /etc/opencpu/server.conf
