### ISSUE TITLE
Reuse results from a previous session?

### ISSUE THREAD

**Issue by joelkuiper** [opencpu/opencpu#286]
We're trying to re-use some outcome of a previous session (long computation) and execute a library function against it. However it does not seem to possible within the session lifecycle of OpenCPU. What would be the recommended way of doing this? 

Currently we tried flushing the results as a side effect, which makes it show up in /files/ but that data is subsequently in-accessible to next requests. 

e.g. (simplified, but it conveys the idea I hope) 

```
POST ocpu/library/mypackage/R/fn

fn <- function(params) { 
 result <- do.compute(params)
 save(result, "./result.Rdata") 
}


POST ocpu/tmp/<prev sess, e.g.x07f258fe79>/R/fn 

a-different-fn <- function(params) { 
 if(file.exists("./result.Rdata") { 
    load("./result.Rdata")
    other.computation(saved.data)
  }
}
```
doesn't work, and `ocpu/tmp/<prev sess, e.g.x07f258fe79>/R/a-different-fn` is also tricky, since that's not exposed under /R/

I could hack around it by requesting the data over HTTP, but that seems silly. Any idea?

**Comment by joelkuiper** [comment]
hacky workaround that might work if the session id is known

```
split_path <- function(x) if (dirname(x)==x) x else c(basename(x),split_path(dirname(x)))

path <- split_path(getwd())
path[2] <- sessionid
path[3] <- "ocpu-store"
path <- paste0("/", paste0(rev(path[2:(length(path)-1)]), collapse="/"))
```

**Comment by jeroen** [comment]
You can use the session ID itself as an argument to any subsequent POST function call, as if it were an R object.

**Comment by joelkuiper** [comment]
Right if the session identifier is known I can just pass it along as a
parameter like any other (and the name is matched the the function
signature). I could then access the data on the file system as per the
snippet above. Or were you proposing something more clever?

**Comment by jeroen** [comment]
Are you aware that opencpu supports this by default? If you pass a session id it will automatically look up the object. For example create an object:

```
Jeroens-MBP:Desktop jeroen$ curl https://cran.ocpu.io/stats/R/rnorm -d n=10
/ocpu/tmp/x04df2cb5a1/R/rnorm
/ocpu/tmp/x04df2cb5a1/R/.val
/ocpu/tmp/x04df2cb5a1/stdout
/ocpu/tmp/x04df2cb5a1/source
/ocpu/tmp/x04df2cb5a1/console
/ocpu/tmp/x04df2cb5a1/info
/ocpu/tmp/x04df2cb5a1/files/DESCRIPTION
``` 

And then I can use this object in a subsequent call:

```
curl https://cran.ocpu.io/base/R/mean -d x=x04df2cb5a1
/ocpu/tmp/x07b47abf53/R/mean
/ocpu/tmp/x07b47abf53/R/.val
/ocpu/tmp/x07b47abf53/stdout
/ocpu/tmp/x07b47abf53/source
/ocpu/tmp/x07b47abf53/console
/ocpu/tmp/x07b47abf53/info
/ocpu/tmp/x07b47abf53/files/DESCRIPTION
```

Or you can also specify the exact object from the session:

```
curl https://cran.ocpu.io/base/R/mean -d x=x04df2cb5a1::.val
```

You don't need to manually lookup any files.

**Comment by joelkuiper** [comment]
Hmm, that gives me 

```
formal argument "x" matched by multiple actual arguments

In call:
toJSON(x = object, pretty = pretty, ...)
```

**Comment by jeroen** [comment]
The `x=` above only is because `mean()` has an `x` parameter right. You just pass it to the parameter of your function.

Have a look at this example: https://rwebapps.ocpu.io/appdemo/www/chain.html (look in browser devtools to see what requests are sent)

**Comment by joelkuiper** [comment]
heh, that works. So tangent, what if actually want the string instead of the object? (just curious how this works)
