### ISSUE TITLE
What are the configuration options?

### ISSUE THREAD

**Issue by phedinkus** [opencpu/opencpu#293]
I'm trying to deploy my opencpu app to Google's App Engine so I can get on-demand auto scaling. Their service requires the application to respond to port 8080 but OpenCPU is set to 8004. I realize I can add settings to the conf file but I'm not sure what my options are so that the port change will get picked up, if possible. Any assistance you can provide would be stellar!

**Comment by jeroen** [comment]
I guess the easiest way would be to edit the port in `/etc/apache2/sites-enabled/opencpu.conf`.

**Comment by phedinkus** [comment]
I'll give it a try and report back. Thanks!
