### ISSUE TITLE
A question about writing a local file

### ISSUE THREAD

**Issue by qwqaijingjing** [opencpu/opencpu#300]
I am a beginner of OpenCPU, I want to call R web service to manipulate local files, my simple R function is this:

hello <- function(x) {

  y="/home/qh/Diamond/bin/a.txt"

  write.table(x,y)

}
   And then , I use command to call this R function, the command is :  

                   curl http://localhost/ocpu/library/mypackage/R/hello -d "x='sdddd'" 

  But, I meet this error:
cannot open the connection
In call:
file(file, ifelse(append, "a", "w"))
 Actually, I can run this function in my Rstudio correctly.
I would appreciate it if anyone can help me.

**Comment by jeroen** [comment]
The webserver needs to have write access to that file. Are you sure
the directory /home/qh/Diamond/bin/ exists and is public writable?

If you run the ubuntu server you have to add a rule to the security
profile, see section 3.5 of the server manual:
https://opencpu.github.io/server-manual/opencpu-server.pdf

**Comment by qwqaijingjing** [comment]
OK, thank you, I will read it.

**Comment by qwqaijingjing** [comment]
Sorry, jeroen, I have read your paper about Rapparmor, and I edited the custom file, like this:
        ## This file is to add custom apparmor policy rules.
       ## You can add rules if your favorite packages need special privileges.
       ##/some/custom/special/dir rwmix,
       /tmp/ rw,
       /tmp/** rwm,
I want the tmp path and its subpath can become readable and writable, but when I run the curl command, I still get the same error.
This is my curl command:
           curl http://localhost/ocpu/library/teste/R/hello -d "x='sss'&y='/tmp/qh/a.txt'"
This is my hello function:
            hello <- function(x,y) {
                   write.table(x,y)
                                             }
And the error is:
       cannot open the connection

        In call:
        file(file, ifelse(append, "a", "w"))
I am very sorry to disturb you two times.
