### ISSUE TITLE
R package graphics call - missing labels in plot - R3.5 openCPU2.0.7 (Debian)

### ISSUE THREAD

**Issue by viswam78** [opencpu/opencpu#306]
Using Ubuntu 18.04, R3.5, openCPU 2.0.7 (from Debian prebuilt binaries) I am failing to generate the labels on an image using one of the R packages. 
However using the R3.4, with the same setting i.e., opencpu-2.0 (from PPA) and Ubuntu 18.04 the labels on the graph shows up. This is just missing labels of the nodes on a network image. However when I use R3.5 and Ubuntu18.04 and run an R script to store the image (not through opencpu calls), the labels show up. Is this a known issue?

**Comment by jeroen** [comment]
The binaries are built against R 3.4 currently which is not compatible with R 3.5 (they changed the ABI, this is beyond my control). So I think you have to rebuild the package from source.

I'll try to build a 3.5 branch soon.

**Comment by viswam78** [comment]
Hi Jeroen, thanks for getting back. We even tried this using the dockerfile from your website:

USER builder
RUN \
  cd ~ && \
  wget https://github.com/opencpu/opencpu-server/archive/v${BRANCH}.tar.gz && \
  tar xzf v${BRANCH}.tar.gz && \
  cd opencpu-server-${BRANCH} && \
  dpkg-buildpackage -us -uc

USER root
RUN \
  apt-get install -y libapache2-mod-r-base && \
  dpkg -i /home/builder/opencpu-lib_*.deb && \
  dpkg -i /home/builder/opencpu-server_*.deb

# Set opencpu password so that we can login
RUN \
  echo "opencpu:opencpu" | chpasswd

**Comment by viswam78** [comment]
Hi Jeroen, More info if it can help debug the issue: One of our team members found that there are missing graph attributes in location of the output data after HTTP POST request i.e., in R/.val (empty .val). This is using new R3.5 and rebuilding the package from source. However, with a previous version (R3.4 +OCPU 2.0.7 +Ubuntu18.04), the R/.val have graph attributes that seem to have information of edges from nodes, along with labels.
<img width="684" alt="screen shot 2018-06-26 at 4 32 57 pm" src="https://user-images.githubusercontent.com/4925178/41937716-0f64df4e-795f-11e8-879b-9b1752fe5dee.png">

**Comment by viswam78** [comment]
Update: If we save the image (for example, using ggsave) and then retrieve from /files/ directory, we were able to see all the graph attributes. So, this works if we use something like http://localhost:8004/ocpu/tmp/x022d8a0c56/files/image.png instead of http://localhost:8004/ocpu/tmp/x0393c55d0e/graphics/1/png, fyi. For now, I will close the issue, because of the alternative fix.
