### ISSUE TITLE
Cannot add PPA: 'ppa:~opencpu/ubuntu/opencpu-2.0' + IPV6

### ISSUE THREAD

**Issue by nikolaof** [opencpu/opencpu#308]
Hi. 

I'm currently trying to install opencpu on an ubuntu server and while executing the `sudo add-apt-repository -y ppa:opencpu/opencpu-2.0`, I got back the following error

> Cannot add PPA: 'ppa:~opencpu/ubuntu/opencpu-2.0'.
> ERROR: '~opencpu' user or team does not exist.

The only clue that I have is that the server has only ipv6 address. Could this be the problem? Does the ppa support access from an ipv6 address?

**Comment by nikolaof** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by nikolaof** [comment]
Ok. I asked for an IPv4 address and problem solved.

**Comment by jeroen** [comment]
Hmm good to know. This is beyond my control, the ppa servers are hosted by ubuntu launchpad.
