### ISSUE TITLE
Update cURL dependency to libcurl4 for opencpu package

### ISSUE THREAD

**Issue by prtksngh** [opencpu/opencpu#309]
Hi Jeroen,

I have installed the "opencpu" package on Ubuntu 18.04.
It installed perfectly, but when running the function `opencpu::ocpu_start_server()` it gives the following error.

> unable to load shared object '/usr/local/lib/R/site-library/curl/libs/curl.so':
>   /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/lib/R/site-library/curl/libs/curl.so)
> 
> In call:
> dyn.load(file, DLLpath = DLLpath, ...)

It seems to be a problem where Ubuntu 18.04 has only libcurl4 and the code expects libcurl3.

So these are the questions that I would like to ask.

1. Would it be possible to update the dependency or remove its usage entirely?
2. Is there a workaround for the libcurl version mismatch?

Finally, I really like what we have with "opencpu" here. It helps the community publish reproducible results. Keep up the great work.

Regards
Prateek

**Comment by jeroen** [comment]
Hmm thanks for letting me know, I'll fix this asap.

**Comment by jeroen** [comment]
How did you install opencpu? The cloud server seems to require the correct versions.

**Comment by jeroen** [comment]
Related: https://github.com/opencpu/opencpu-server/commit/fb70e56feeaaa5f68e4c9cc5b9b344a388121d7c

**Comment by prtksngh** [comment]
Thanks for the quick amendment. It worked that time. Sorry for the late reply, just saw it now. I will close this now.
