### ISSUE TITLE
options(warn=2) ignored in tryCatch

### ISSUE THREAD

**Issue by zerweck** [opencpu/opencpu#310]
To ensure production code returns no unexpected results my main function (replaced by `asin()` in the following example) is wrapped in an outer api function containing `options(warn=2)` (converting all warnings to errors) in the first line and then a tryCatch with a calling handler for errors only. It looks something like this:
```R
my_api <- function(x) {
    options(warn=2)
    tryCatch(expr = asin(x),
             error = function(this_error) {print(this_error);print("there was an error")}
    )
}
```

When running locally, this ensures all warnings are returned to errors and the calling handler is invoked, logging the message etc.
```R
> my_api(-1)
[1] -1.570796
> my_api(2)
<simpleError in asin(x): (converted from warning) NaNs produced>
[1] "there was an error"
```

However, in the second case our OpenCPU Server only returns the NaN result, and does not run the error calling handler. It only does so if there is an actual error, like this:
```R
> my_api("non-numeric input")
<simpleError in asin(x): non-numeric argument to mathematical function>
[1] "there was an error"
```

So it seems to me that the options(warn=2) gets overridden somewhere, since tryCatch is able to read the calling handler for actual errors just fine. Any ideas where this might come from and how to circumvent this behaviour?

**Comment by jeroen** [comment]
You should change the global warning handler inside your function call, because as you noticed other parts of the system may rely on this. Why don't you set the `warning` handler directly like this?

```r
my_api <- function(x) {
  tryCatch(expr = asin(x),
           warning = function(err) {stop(err)}
  )
}
```

**Comment by zerweck** [comment]
Thanks, this is also how I circumvented this particular problem in my case. But I am still trying to find out what causes the behaviour, since it may be a non-documented difference between a local interactive R session and an OpenCPU R Session.

**Comment by jeroen** [comment]
I think it is because `evaluate` relies on these handles to evaluate the code:

```r
evaluate::evaluate('my_api(2)')
```
