### ISSUE TITLE
Update R Version for Dockerhub opencpu/base/

### ISSUE THREAD

**Issue by leonatpanda** [opencpu/opencpu#313]
R version for opencpu/base/ Docker image is set to 3.4.4

Is there a particular reason why? To run more recent version of R, do we have to build from source?

**Comment by jeroen** [comment]
I'm working on it, but it's a bit of a process because of the ABI changes in R 3.5. Plan to switch to ubuntu bionic with R 3.5.1 next week.

**Comment by jeroen** [comment]
The [base](https://hub.docker.com/r/opencpu/base/), [rstudio](https://hub.docker.com/r/opencpu/rstudio/), and [apps](https://hub.docker.com/r/opencpu/apps/) images have now been updated to Ubuntu Bionic with R 3.5.1
