### ISSUE TITLE
preLoad data

### ISSUE THREAD

**Issue by mfazel** [opencpu/opencpu#318]
Hi,

I'm using opencpu 2 in a docker container and have to load a big data file upfront.
Is it normal that after the container is up and running, it uses a lot of machine's memory? Say for example 2~3 times as if data was loaded in pure R?

Thanks

**Comment by meztez** [comment]
You container load multiple instance of R to answer to respond to concurrent requests, this is set by /etc/apache2/mods-available/mpm_prefork.conf in the container.

So your container would use StartServers * Required memory for one R instances.

This is described here :
https://stackoverflow.com/questions/47419387/high-memory-usage-in-opencpu

**Comment by mfazel** [comment]
Yes, that's correct. I figured it out last year but forgot to mention it here. 
Thanks.
