### ISSUE TITLE
opencpu using older package version causing problems

### ISSUE THREAD

**Issue by dredan** [opencpu/opencpu#323]
Hi,

After updating some packages on the server to newer versions, i was getting errors like `namespace 'Rcpp' 0.12.14 is already loaded, but >= 0.12.19 is required` even though i have much higher version in my R lib. it turns out the opencpu lib has the 0.12.14 old version and somehow its getting referenced by my R setup. i tried updating open cpu using apt-get / upgrade but still contains old version of Rcpp. I know this seems to be duplicate issue but I tried all suggestions. thanks.

**Comment by jeroen** [comment]
When you have a chance try upgrading to opencpu 2.1. That should resolve the problem. Note that this also upgrades to receive 3.5.

**Comment by dredan** [comment]
thank you, that fixed it.

**Comment by jeroen** [comment]
Great, thanks for confirming.
