### ISSUE TITLE
Opencpu and Microsoft R Open

### ISSUE THREAD

**Issue by MarcelloModica** [opencpu/opencpu#326]
Could someone help me on understand if m$ R open is fully compatible with opencpu? If yes how to install it and test it in a container?  Thanks in advance for your suggestions.

**Comment by lello1978** [comment]
Yes we want to try the advantage of multiple cores. Do you think is it the right way? What do you suggest? 

sent on the go.
scusate brevità od errori


   Jeroen Ooms --- Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326) --- 
    Da:"Jeroen Ooms" <notifications@github.com>A:"opencpu/opencpu" <opencpu@noreply.github.com>Cc:"lello1978" <marcello.modica@logconsulting.it>, "Author" <author@noreply.github.com>Data:dom, 30 dic 2018 14:25Oggetto:Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326)
  
  I think MS R doesn't support Ubuntu Bionic right now? Why would you want to use MS R instead of the real R?

**Comment by jeroen** [comment]
R has many packages that do parallel processing. These packages are the same between GNU R and MS R, so you wont gain any performance with MS R.

**Comment by lello1978** [comment]
So there isn't no reason to use MS  R?  In the container you provide in dokerhub which version of R is installed? Does it use some packages for math improvement? 

sent on the go.
scusate brevità od errori


   Jeroen Ooms --- Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326) --- 
    Da:"Jeroen Ooms" <notifications@github.com>A:"opencpu/opencpu" <opencpu@noreply.github.com>Cc:"lello1978" <marcello.modica@logconsulting.it>, "Author" <author@noreply.github.com>Data:dom, 30 dic 2018 16:49Oggetto:Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326)
  
  R has many packages that do parallel processing. These packages are the same between GNU R and MS R, so you wont gain any performance with MS R.

**Comment by lello1978** [comment]
Thanks in advance 

sent on the go.
scusate brevità od errori


   Jeroen Ooms --- Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326) --- 
    Da:"Jeroen Ooms" <notifications@github.com>A:"opencpu/opencpu" <opencpu@noreply.github.com>Cc:"lello1978" <marcello.modica@logconsulting.it>, "Author" <author@noreply.github.com>Data:dom, 30 dic 2018 16:49Oggetto:Re: [opencpu/opencpu] Opencpu and Microsoft R Open (#326)
  
  R has many packages that do parallel processing. These packages are the same between GNU R and MS R, so you wont gain any performance with MS R.

**Comment by nainai123** [comment]
Have you solved this problem now, please? I'm working on this but nothing is happening right now. If you solved it please get back to me thanks.

**Comment by jeroen** [comment]
We don't support Microsoft R. Also Microsoft has stopped developing MS open R and recommends you use regular R.

**Comment by nainai123** [comment]
> 我们不支持 Microsoft R。此外，Microsoft 已停止开发 MS open R，并建议您使用常规 R。

Thank you, so I can get off work. This is something I've been trying for a week. Have fun every day. Best wishes from China
