### ISSUE TITLE
OpenCPU cannot return value between 1e-05 to ~1e-04 correctly

### ISSUE THREAD

**Issue by slfan2013** [opencpu/opencpu#328]
Strange that OpenCPU cannot display the values between 1e-05 to ~1e-04 correctly. All these values will be returned as exact 0.

Here is the R code,
```
test_bug = function(){
  # genrate values from 1e-05 to 1e-04
  data = data.frame(value = c(seq(0.00001,0.0001,by=0.0000001)))
  return(data)
  }
```
There is no error in the format of `print` or `csv`. However, the format of `json` is incorrect.
The url of `http://localhost:5656/ocpu/tmp/x0567909793/R/.val/print` would return 
```
        value
1   0.0000100
2   0.0000101
3   0.0000102
4   0.0000103
5   0.0000104
...
```

There is no error in the format of `print` or `csv`.  However, `session.getObject(function(obj){console.log(obj[1])})`, my `obj[1]`, and also`obj[2]` etc,  are exact zero. 

I am working on very small p-values, so it is very important to have accurate number of digits..

**Comment by jeroen** [comment]
I think this is due to the default `digits` argument in jsonlite::toJSON(). Can you try appending `?digits=10` to your url?

**Comment by slfan2013** [comment]
@jeroen 
Thank you for your help!

the `?digits=10` and `use_signif=true` does work. 

However, what I am trying to do is getting the right digits within the 

```
session.getObject(function(obj){
    obj[1] // I would like to have this number correct
})
```

I wonder is there a way, or parameter, that can make `obj` having right numbers?

**Comment by jeroen** [comment]
> Or I can change the var url = this.getLoc() + "R/" + name + "/json"; in my opencpu.js?

Yes that's the best solution. I should probably make this the default...
