### ISSUE TITLE
Possible disable Opencpu fromJSON inside function ?

### ISSUE THREAD

**Issue by kcomin** [opencpu/opencpu#335]
Hello,

I am currently testing Opencpu in my R project.
I understand that Opencpu automatically converted the json to object R in function.

However, it use jsonlite package who convert list in JSON to dataframe.
I would like to keep my lists. Would it be possible to **disable automatic opencpu conversion to function input**? i could convert then with the **rjson or RJSONIO** package that keeps the list structure.

My JSON object to send with curl :
```
{
  "cars": [
    {
      "id": 1,
      "type": "TYPE1",
      "accessories": [
        {
          "id": 1,
          "type": "AC1",
          "mark": {
            "name": "m1",
            "num": 145
          },
          "wheel": null
        },
        {
          "id": 2,
          "type": "AC2",
          "mark": {
            "name": "m2",
            "num": 147
          },
          "wheel": {
            "id": 1,
            "size": null
          }
        }
      ]
    }
  ]
}
```
I would like to create my own from json inside my function like :
```
myfunction <- function(cars) {

  RJSONIO::fromJSON(cars)
  
  ...
}
```
Thank you in advance

**Comment by jeroen** [comment]
If you post the data as a regular string (wrapped in quotes and properly escaped) then it won't be converted.

**Comment by kcomin** [comment]
Thanks for help ! :)
