### ISSUE TITLE
Non-standard evaluation and OpenCPU: Passing expressions using Protocol Buffers to remote server

### ISSUE THREAD

**Issue by ablaette** [opencpu/opencpu#336]
Dear colleagues, 

thank you so much for what you have created. I am really fascinated by the possibilities of sending/receiving data to an OpenCPU server using Protocol Buffers, i.e. using `rprotobuf` in combination with the `httr`-package. (Please let me know whether this is rather a rprotobuf issue.)

I recently encountered a set of problems I do not understand entirely when trying to send unevaluated expression to a remote server. 

My scenario is to have his subsetting operation executed on an OpenCPU server. Locally it would be:

```r
subset(iris, Sepal.Width > 4.0)
```

But I do not manage to execute this on the OpenCPU server directly. The following code throws a "Bad Request (HTTP 400)."-error.

```r
library(RProtoBuf)
library(httr)
args <- list(x = iris, subset = substitute(Sepal.Width > 4.0))
resp <- httr::POST(
  url = "https://cloud.opencpu.org/ocpu/library/base/R/subset/pb",
  body = RProtoBuf::serialize_pb(args, NULL),
  httr::add_headers("Content-Type" = "application/protobuf")
)
httr::stop_for_status(resp)
```

Now, something that works is to use a `do.call` workaround:

```r
args <- list(what = "subset", args = list(x = iris, subset = substitute(Sepal.Width > 4.0)))
resp <- httr::POST(
  url = "https://cloud.opencpu.org/ocpu/library/base/R/do.call/pb",
  body = RProtoBuf::serialize_pb(args, NULL),
  httr::add_headers("Content-Type" = "application/protobuf")
)
httr::stop_for_status(resp)
RProtoBuf::unserialize_pb(resp$content)
```

However, passing into `do.call` a function from another (self-written) package does not work smoothly, because namespaces seem to be sealed against each other, i.e. in the environment of the `base` package, the names of another package apparently remain unknown. I can make some progress by prepending otherpackage:: to any method/function used, but having to do this throughout my other package is awful.

Trying to find a solution on my own, I resorted to deparsing the expression I want to transmit into a character vector, and to parse the expression again on the remote machine (using something like `parse(text = "Sepal.Width > 4.0")`). 

But I am not sure whether this can be the appropriate solution. Is there any elegant solution to the problem?

Andreas

**Comment by jeroen** [comment]
Cool question. Indeed the protobuf format only supports data types, and not expressions. But what you can do is do a POST request in which one of the fields in encoded as protobuf. Also please use protolite instead of RProtoBuf.

```r
library(protolite)
library(httr)
res <- httr::POST(
  url = "https://cloud.opencpu.org/ocpu/library/base/R/subset/pb",
  body = list(
    x = curl::form_data(protolite::serialize_pb(iris), "application/protobuf"),
    subset = 'Sepal.Width > 4.0'
  )
)
httr::stop_for_status(res)
protolite::unserialize_pb(res$content)

```

**Comment by ablaette** [comment]
Thanks so much for your quick response and your advise. It works like a charm, and this is the real-world example I now have a solution for without my dirty hack.

This is what I CAN do locally with the polmineR package (creating a subcorpus of a "REUTERS" corpus by subsetting the corpus using nse):

```r
if (!"polmineR" %in% rownames(installed.packages())) install.packages("polmineR")
library(polmineR)
subset("REUTERS", grep("saudi-arabia", places))
```
Then you have a subcorpus for articles on Saudi-Arabia. And this is how subsetting a remote corpus works now:

```r
library(protolite)
library(httr)

res <- httr::POST(
  url = "http://185.73.20.140/ocpu/library/polmineR/R/subset/pb",
  body = list(
    x = curl::form_data(protolite::serialize_pb("REUTERS"), "application/protobuf"),
    subset = 'grep("saudi-arabia", places)'
  )
)
httr::stop_for_status(res)
protolite::unserialize_pb(res$content)
```

Thanks a lot indeed! Let's close the issue?
