### ISSUE TITLE
ocpu_start_app() does not show updated webpage

### ISSUE THREAD

**Issue by TianrenWang** [opencpu/opencpu#343]
Operating system: macOS 10.13.6
R version: 3.6.0

git repository: https://github.com/bhklab/DNF2/tree/test-index

I run the R project, build and import the project as an R package, and perform the following commands on RStudio console:

```
library(opencpu)
ocpu_start_app("DNF2")
```

If this is the first time you run the app locally, then ocpu might perform some GET requests to fetch the websites in the "inst" folder, but the GET requests are no longer performed if you stop the console and run ```ocpu_start_app("DNF2")``` again. Restarting RStudio or the computer doesn't fix the problem. Another weird thing is that opencpu fixates on the same unchanged html files that were used during the first time I called ```ocpu_start_app()```. This is a huge problem because none of the local updates I make to my html files show up. Changes that I make to the github repository DOES show up, however, so this is a purely local issue. But I also don't want to push the changes to remote every time I update my website, I rather see the change take place locally before pushing.

**Comment by jeroen** [comment]
Did you try pressing ctrl+shift+R in your browser to force a refresh? THe browser might show you a cached version.

Also try `ocpu_start_app("bhklab/DNF2")`

**Comment by TianrenWang** [comment]
Thank you. The force refresh updated the page.
