### ISSUE TITLE
Reuse results from previous session not working when using Windows or Localhost

### ISSUE THREAD

**Issue by slfan2013** [opencpu/opencpu#345]
I would like to use `save_iris_as_csv` to save a _.csv_ file. Then, call `catch_url_and_download` to download this _.csv_ file using the session returned by `save_iris_as_csv`. However, the `catch_url_and_download` does not work, returning an error of 

```
OpenCPU error HTTP 400
cannot open URL 'http://localhost:5656/ocpu/tmp/x06c27c3ac4/files/iris.csv'

```

Following is my javascript code.

```
ocpu.call("save_iris_as_csv",{},function(session){
    console.log("save_iris_as_csv is good.")
    console.log(session)
    console.log("trying to call catch_url_and_download.")
    ocpu.call("catch_url_and_download",{
        url:session.loc + "files/iris.csv"
    },function(session2){
        console.log(session2)
    }).fail(function(e){
        console.log("catch_url_and_download failed. Cannot open URL xxx.")
        alert(e.responseText)
    })
})

```

Following is my R codes.

```
save_iris_as_csv = function(){
  write.csv(iris,"iris.csv")
}
catch_url_and_download = function(url){
  download.file(url,"iris.csv")
}

```

I am using Windows OS.

**Comment by Norquant** [comment]
I think this has something to do what download.file, because this function triggers a download pop-up.
You probably dont have permission to do this. 
If you replace download.file(url,"iris.csv"), it works and correct download link gets passed. Maybe better idea to just pass this link, and the user can click it.

**Comment by slfan2013** [comment]
Thanks. 

Actually, I think it is because of something with Windows or localhost. I deployed with my demo R package with opencpu cloud and found it works ([https://slfan2013.ocpu.io/testingURL/www/](https://slfan2013.ocpu.io/testingURL/www/)).

However, it just does not work with Windows or my localhost. I don't know the reason.

**Comment by Norquant** [comment]
Im on a mac and it didnt work here either, so probably something with localhost yeah.

**Comment by slfan2013** [comment]
Jeroen has answered this question [here](https://stackoverflow.com/questions/56636184/opencpu-reuse-results-from-previous-session-not-working).

**Comment by slfan2013** [comment]
Jeroen has answered this [here](https://stackoverflow.com/questions/56636184/opencpu-reuse-results-from-previous-session-not-working).
