### ISSUE TITLE
400 - Bad Request - No method asJSON S3 class: htest when doing and adf test

### ISSUE THREAD

**Issue by anback** [opencpu/opencpu#351]
Hi! 

Awesome work with OPenCPU! Really promising tech! I only added this issue for your information and to contribute, i am happy parsing text :) See pic and see headline, i get a 400 when trying to do a tseries/adf.test, when i omit the /json suffix in url it works. 

Cheers
Anders

![image](https://user-images.githubusercontent.com/2440382/63206550-cd275a80-c0b6-11e9-8f5c-d961494d1b64.png)

**Comment by jeroen** [comment]
This simply means that the object you are retrieving cannot be converted to json by `jsonlite::toJSON()`. Only core R types (vectors, data frames, etc) can be converted to json.
