### ISSUE TITLE
Failed to load /etc/opencpu/Renviron

### ISSUE THREAD

**Issue by mbacou** [opencpu/opencpu#356]
Hi, I have packages that require DB connection user/pass, but adding these environment variables to `/etc/opencpu/Renviron` has no effect. All requests fail with:
 
`FATAL:  Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.`

I also tried adding `Sys.setenv(...)` to `/etc/opencpu/Rprofile`. That has no effect either. 

Am I missing something?
Thanks

```
> apt list opencpu*
Listing... Done
opencpu-cache/xenial 2.1.6-xenial0 all
opencpu-full/xenial 2.1.6-xenial0 all
opencpu-lib/xenial,now 2.1.6-xenial0 amd64 [installed,automatic]
opencpu-server/xenial,now 2.1.6-xenial0 all [installed]
opencpu-tex/xenial 2.1.6-xenial0 all
```

**Comment by jeroen** [comment]
That looks correct. You can try something like this to print the variables:

```
curl -LX POST https://cloud.opencpu.org/ocpu/library/base/R/Sys.getenv/print
```

**Comment by mbacou** [comment]
@jeroen thanks for the tip, yes that's printing the 2 ENV variables as expected. I used outdated package options, my bad.
