### ISSUE TITLE
DENIED cannot start processx process '/usr/local/bin/phantomjs' 

### ISSUE THREAD

**Issue by Tartomas** [opencpu/opencpu#357]
Hello, thanks for your project. I'm facing an issue with phantomJS. I have installed it as recommend in [webshoot](https://github.com/wch/webshot), from ssh terminal and from rstudio/server IDLE in my Ubuntu 18 server running with open-cpu service properly. In both cases I can find it and works. The problem es when I call API endpoint using a regular  POST. It appear the following issue.

```
Error:
cannot start processx process '/usr/local/bin/phantomjs' (system error 13, Permission denied) @unix/processx.c:592 (processx_exec)
```
then I **cat /var/log/kern.log** and this is the answer
```
Mar 13 23:58:59 cool_package kernel: [ 2911.094138] audit: type=1400 audit(1584143939.651:50): apparmor="DENIED" operation="exec" profile="opencpu-exec" name="/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs" pid=5373 comm="apache2" requested_mask="x" denied_mask="x" fsuid=33 ouid=0
```

My **/etc/apparmor.d/opencpu.d/custom** looks like

```
/usr/local/bin/** rw,
/ r,
/** r,
/* r,
/etc/opencpu/ rwmix,
```

I also try [this setup installation](https://stackoverflow.com/questions/48702133/phantomjs-not-found-on-shiny-server) of **phatomjs** but neither work

I'd really appreciate any hand on this. 
Tomás

**Comment by jeroen** [comment]
In your `/etc/apparmor.d/opencpu.d/custom` you need to add:
```
/usr/local/bin/** rwmix,
```
The `ix` is needed to run (exec) executables.

**Comment by Tartomas** [comment]
Thanks Jeroen, work perfectly!

**Comment by mbacou** [comment]
Hi @jeroen, could apparmor also pose problems with pandoc executable? E.g. I have an endpoint that starts an async R process with `system("Rscript -e 'rmarkdown::render(...)'")` and was never able to get that to work via POST:

```
Mar 23 23:17:31 data-analysis kernel: [173791.730301] audit: type=1400 audit(1585005451.779:39): apparmor="DENIED" operation="open" profile="opencpu-exec" name="/etc/gss/mech.d/" pid=33661 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=0

```
Thanks!

**Comment by jeroen** [comment]
The error message says that it is blocking a read call to `/etc/gss/`. I think these files have to do with GSS authentication, I don't think is related to pandoc...

But you can easily test it by permitting those files in `/etc/apparmor.d/opencpu/custom`
