### ISSUE TITLE
Use of opencpu with the dbplyr library when I don't use the dbplyr::collect() function

### ISSUE THREAD

**Issue by PauloJhonny** [opencpu/opencpu#359]
Hi.

I am using `opencpu` in production and it's really amazing. Thank you.

However, I have doubts regarding its use together with the `dbplyr` library when I don't use the `dbplyr::collect()` function, which is used to pull the queried data from a database into R's memory. All I want is that my function hosted in `opencpu` returns a `dbplyr` object.

For example, let's say my function hosted in `opencpu` queries the mtcars table from a SQL Server database:

```
function_hosted_opencpu <- function (driver = "SQL Server",
                                     server = "xxx",
                                     port = "1433",
                                     database = "xxx",
                                     login = "xxx",
                                     passwd = "xxx",
                                     encod = "UTF-8") {

odbcConnection <- DBI::dbConnect(odbc::odbc(),
                                 driver = driver,
                                 database = database,
                                 uid = login,
                                 pwd = passwd,
                                 server = server,
                                 host = server,
                                 port = port,
                                 encoding = encod,
                                 identifier.quote="`")
  
dplyr::copy_to(odbcConnection, mtcars)
mtcars2 <- dplyr::tbl(odbcConnection, "mtcars") # no dplyr::collect()

return(list(odbcConnection = odbcConnection,
            mtcars2 = mtcars2))

}
```
If I print the `function_hosted_opencpu` mtcars2 results, it just retrieves the first few rows. And all dplyr calls are evaluated lazily, generating SQL that is only sent to the database when you request the data:

```
function_hosted_opencpu(...)$mtcars2

#> # Source:   table<mtcars> [**??** x 11]
#> # Database: sqlite 3.25.3 [:memory:]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4
#>  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
#>  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1
#>  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1
#>  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2
#>  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1
#>  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4
#>  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
#>  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
#> 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4
#> # … with more rows
```
If I use the `collect()` function in the `function_hosted_opencpu` function I will get all the dataframe in memory in R. But I don't want it. I want to get the `dbplyr` object without using the `collect` function.  

So I tried to do that, but I'm struggling when I need to do a POST request like this:

```
req <- httr::POST("http://opencpu.server/ocpu/library/my_library/R/function_hosted_opencpu",
                  body = list(driver = "SQL Server",
                              server = "xxx",
                              port = "1433",
                              database = "xxx",
                              login = "xxx",
                              passwd = "xxx",
                              encod = "UTF-8"),
                  encode = "json",
                  httr::add_headers("Content-Type" = "application/json", 'charset' = 'utf-8'))

req

Response [http://opencpu.server/ocpu/library/my_library/R/function_hosted_opencpu]
  Date: 2020-03-31 19:51
  Status: 201
  Content-Type: text/plain; charset=utf-8
  Size: 243 B
/ocpu/tmp/x0467603d52c0da/R/.val
/ocpu/tmp/x0467603d52c0da/R/SQLcon
/ocpu/tmp/x0467603d52c0da/stdout
/ocpu/tmp/x0467603d52c0da/source
/ocpu/tmp/x0467603d52c0da/console
/ocpu/tmp/x0467603d52c0da/info
/ocpu/tmp/x0467603d52c0da/files/DESCRIPTION

get <- httr::GET(paste0(req$all_headers[[1]]$headers$location, "stdout"))

get

Response [http://opencpu.server/ocpu/library/my_library/R/function_hosted_opencpu]
  Date: 2020-03-31 19:52
  Status: 200
  Content-Type: text/plain; charset=utf-8
  Size: 50 B
**List of length  3 
[odbcConnection]
[mtcars2]**
```
 How can I get the list of the elements, which in this case are the odbcConnection object and the mtcars2 object (doesn't collected)?

I tried to use this, but It didn't work:

`httr::content(get, type="application/json")`

> 
> Error: lexical error: invalid char in json text.
>                                        List of length  3  [odbcConnect
>                      (right here) ------^

or 

```
get <- httr::GET(paste0(req$all_headers[[1]]$headers$location, "R/.val/json"))
httr::content(get, type="application/json")
```

> Error: lexical error: invalid char in json text.
>                                        No method for S4 class:Microsof
>                      (right here) ------^
> 

Thank you.

**Comment by jeroen** [comment]
I don't understand, what do you expect to get when you download the `odbcConnection` object? It's a type of object that doesn't contain data, it cannot be serialized to json. 

You can use `R/.val/print"` to get see what it would look like in the console, if that is what you are after.

**Comment by PauloJhonny** [comment]
@jeroen, thank you!

I put the `odbcConnection` in a list because I wanted to close it in another function. But, now, I understand It can’t be serialized.

I will try to let just the `mtcars2` in the return of the function and see the output of the `R/.val/print`.

When I use `dplyr::collect()` in the function, it works really well because the output is a json that can be transformed into a tibble/dataframe:

```
get <- httr::GET(paste0(req$all_headers[[1]]$headers$location, "R/.val/json"))
httr::content(get, type="application/json")
```

But without using `dplyr::collect()`, I don’t know yet if I can use the output. 

Again, thank you very much.

**Comment by jeroen** [comment]
Yes you can only store and retrieve actual data. Not the database connection itself.
