### ISSUE TITLE
Console output doesn't mimic console as shown in R studio or R console

### ISSUE THREAD

**Issue by zalazhar** [opencpu/opencpu#363]
Hi Jeroen,
I would expect that the session console output as generated by an OCPU post would mimic the console output as shown in "Rstudio" or the "R graphic interface". That is not the case for the following example: 

> curl https://cloud.opencpu.org/ocpu/apps/zalazhar/reticulate_ocpu/R/executepyth  -d "string='print(3*2)'"

The OCPU post returns a console with an empty output while in Rstudio or the R graphic interface returns 6 as I would expect:

OCPU console (https://cloud.opencpu.org/ocpu/tmp/x01c08bc934eda8/console/text):

<img width="722" alt="Screen Shot 2020-06-23 at 6 29 52 PM" src="https://user-images.githubusercontent.com/10079810/85429870-a2801b00-b57f-11ea-98f0-acc1ec90a5e6.png">

Whereas in Rstudio or basic R graphic interface the called functions returns 6:

<img width="433" alt="Screen Shot 2020-06-23 at 6 21 25 PM" src="https://user-images.githubusercontent.com/10079810/85429315-d9096600-b57e-11ea-9165-86ee4d7698d1.png">

Is this a bug? Or a setting that must be set? Is it related to the reticulate package? Why is there difference in behavior between the OCPU concole and R console ? 

Kind regards,
Zakaria

**Comment by zalazhar** [comment]
It might be related to the fact that I'm using another R version (4) than the OCPU server (3.6). Will test locally on R 3.6 to see I get the same behavior as the server. If that is the case I can close the issue.

**Comment by jeroen** [comment]
Are you sure your function __returns__ 6? Can you save the output to a variable? If you're calling out to python, it may be that python prints something to the stdout that is not part of R.

**Comment by zalazhar** [comment]
> Are you sure your function **returns** 6? Can you save the output to a variable? If you're calling out to python, it may be that python prints something to the stdout that is not part of R.

No the function doesn't return 6, sorry for not formulating this well. The function receives a (python code) string, which is executed in Python. In this specific case, my python string is as follows: "print(3*2)", this **_prints_** out in **R console** 6 when I execute the function. I don't see this behavior in the OCPU console, which I would expect do the same as the R console. 

I can save the output to a variable , but that is not my case here, as it will be converted to an R object. I want to make use of the R console output "as is".  

> prints something to the stdout that is not part of R.
That is not case as I've tested the same function in R which prints 6 to the console. Even used capture.output which returns 6 as well.

**Comment by jeroen** [comment]
In R, if you wrap the code in `capture.output()` are you able to store the output string that way?

If somethings gets printed directly to stdout by the python subprocess, we may not be able to capture it.

**Comment by zalazhar** [comment]
Ok, this was so confusing.  Indeed, when I save it to a variable via capture.output() then the variable is empty. What was confusing is that the R console kept printing 6, also during saving via capture.output(). In that sense, OpenCpu is consistent with R -> will close the issue. 

> If somethings gets printed directly to stdout by the python subprocess, we may not be able to capture it.
OK, this becomes somewhat technical for me.  Somehow R is able to capture the python output, probably an reticulate setting or a reticulate function that I'm that I'm not aware of -> will investigate furhter.

Thanks for your time and help.

**Comment by zalazhar** [comment]
capture.output() gives same behavior as OCPU console, therefore closed. Somehow R is able to capture the python output in the R console window, but that is probably done through a reticulate setting or function -> will investigate further.

**Comment by zalazhar** [comment]
On a sidenote: looking deeper into the reticulate package, I found the the functions to capture python output with which I can capture the python output: py_capture_output(py_run_string(string))
