### ISSUE TITLE
Reuse raw uploaded file

### ISSUE THREAD

**Issue by JeremyPasco** [opencpu/opencpu#371]
Hi,
I try to create a solution allowing a user to upload a big file once and then to try different parsing methods on it without reuploading it everytime.

I know I can do something like this :

- POST a CSV file to /read.csv
- then POST to /my_function with a file param using the key value obtained from the previous call

But I can't be sure that read.csv will work. So I'd like to keep the result of the first call as a raw file stored in cache, and parse it only during subsequent calls.

I tried a different approach with a function like this :

```
upload_file <- function (file) {
   file
}
```

Which does nothing but would allow me to cache the file with a POST :

- POST a file to /upload_file
- get the resulting key
- POST to /parsing_method_one with file=key

Doing so I get this error : 'x05d3e6b41a40c3' does not exist in current working directory ('/tmp/ocpu-temp/x0f64319c9547f4/workspace').

Does it mean that only R data (matrix, dataframe...) can be reused between calls through cache key ? Is there an alternative for raw data ?

**Comment by jeroen** [comment]
opencpu itself does not have a file storage like that. If you are running your own server, I you could use the initial call to save the file somewhere on disk or into a database.

But wouldn't it be easier if you combine all those parsing methods into a single function with some `tryCatch()` blocks?

**Comment by JeremyPasco** [comment]
Thanks for your quick reply.
I'm afraid that some `tryCatch` wouldn't work. My scenario was oversimplified. Files are raw data extracted from medical devices, which failed to respect standard formats. These files are huge (many Go) and parsing methods may vary a lot depending on the use case and can be very opinionated. I can't afford to try all of them (would take many days), but an experienced user could find a good method after a few calls, depending on errors showed during previous tries.

I'll look into a dedicated storage solution as you mentionned, but just to be sure before that : after a call to my do-nothing `upload_file` function, I can do a GET request on /ocpu/tmp/{key}/files/data.csv
Which allows me to retrieve the uploaded file. So it seems that opencpu stored me file somewhere. Can't I reuse this one in next calls?

**Comment by jeroen** [comment]
> So it seems that opencpu stored me file somewhere. Can't I reuse this one in next calls?

Not really, the system is designed so that it can be distributed, so the only way to get that file is retrieving it from that URL. Of course you can `curl::download_file()` from there in your subsequent calls.

But it sounds like what you need is something else running on your server to hold the files, for example a simple db like redis, or even just a fileserver. Then your R functions can pull in data from there.

**Comment by JeremyPasco** [comment]
Ok thanks a lot for your answer.
I will try a fileserver (Redis would take too much RAM for my use case).

However I finally managed to do it with the key solution by registering my file into a raw vecor like this :

```r
upload_file <- function(file) {
   readr::read_raw_file(file)
}
```

Since most parsing functions accepting a file also allow raw vector, it fits my needs for prototyping.
