### ISSUE TITLE
Adding a font to the opencpu cloud server 😊

### ISSUE THREAD

**Issue by annafergusson** [opencpu/opencpu#375]
Kia ora Jeroen 

I'm using opencpu to make interactive web-based coding tasks for my intro stats students and it's amazing - thank you (and anyone else in your team) so much! The only very-non-serious issue I have is that one of our tasks involves making memes using the awesome {magick} package but it appears the **Impact** font is not available on the cloud server. Unfortunately, none of the other fonts available have quite the same ..... impact 😊 ... when it comes to making memes (e.g. UnYetgul). Would it possible at all to add the Impact font or another font similarly meme-able to the cloud server? I totally understand this not being a priority, however!

![](https://memegenerator.net/img/instances/61797216.jpg)

**Comment by jeroen** [comment]
Hmm good question. I just installed the `ttf-mscorefonts-installer` package on the server, which should contain a bunch of microsoft fonts. Can you test if this worked?

**Comment by annafergusson** [comment]
Yes it did - amazing thanks so much! Here’s some evidence 😺
![A9B5BCA7-A7F7-4B6C-995F-E1FAE44906EC](https://user-images.githubusercontent.com/24468501/102884765-1069b880-44b7-11eb-8188-d79aaa192f92.png)

**Comment by jeroen** [comment]
Very impressive 😸

**Comment by annafergusson** [comment]
Hello again! Maybe I’m doing something wrong but the fonts seem to have disappeared cloud server. 🤔
