### ISSUE TITLE
X11 and the session graphics API

### ISSUE THREAD

**Issue by blueraleigh** [opencpu/opencpu#376]
I'm learning to use the wonderful opencpu API (single server session) but am running into trouble with session graphics. 

It seems that `httpget_object_png` introduces a dependency on X11 because it specifies `png(type="cairo")`. So that without X11 the following error is returned 

```r
X11 is not available

In call:
png(type = "cairo", file = mytmp, width = as.numeric(width), 
    height = as.numeric(height), pointsize = as.numeric(pointsize), 
    ...)
```

I was just wondering if this was intentional as the default behavior of `png` is to choose the appropriate type automatically via `getOption("bitmapType")`. 

In a regular R session I have no trouble with the `png` function because it knows to select `quartz` on my system.

Thanks!

**Comment by jeroen** [comment]
I think the idea is that we use cairo when available:

https://github.com/opencpu/opencpu/blob/94ac0046e5e30ffae1dce8676817d73cbe443803/R/settings.R#L53-L55

**Comment by blueraleigh** [comment]
`capabilities` tells me that `capabilities("cairo")` and `capabilities("png")` are ` FALSE` but that `capabilities("aqua")` is `TRUE`. According to the docs

```r
Capabilities '"jpeg"', '"png"' and '"tiff"' refer to the X11-based
versions of these devices.  If 'capabilities("aqua")' is true,
then these devices with 'type = "quartz"' will be available
```

My understanding is that these lines
https://github.com/opencpu/opencpu/blob/3e95a7b796d011a92d97497a267ebdcf4b430033/R/httpget_object.R#L210-L212

by specifying `type="cairo"` cause the `png` function to skip over the [conditional](https://github.com/wch/r-source/blob/d22ee2fc0dc8142b23eed9f46edf76ea9d3ca69a/src/library/grDevices/R/unix/png.R#L45) that would otherwise call `getOption("bitmapType")` and return "quartz"
