### ISSUE TITLE
Is it possible to return a JSON when R raises an error, instead of `text/plain`?

### ISSUE THREAD

**Issue by eduardokapp** [opencpu/opencpu#378]
Can I control the content-type when there's an error? More so, could I return HTTP 400 in other situations (e.g. not errors)?

**Comment by Salatbesteck** [comment]
Regarding the content type, at the current stage the error message can't be controlled by clients or by openCPU server configurations. Error messages are always returned as plain text. 

As the error message is always just a plain string, I can't see a big benefit in converting it into JSON format. A simple check based on the status code should resolve any issues in client applications.

Regarding the status codes, these are controlled by openCPU only.  Status codes are managed within the res object.  The logic on how the status codes are set can be obtained from the package documentation.

**Comment by eduardokapp** [comment]
So the answer is: no, it is not possible?

**Comment by Salatbesteck** [comment]
Yes, without changes of the OpenCPU package, this is not possible
