### ISSUE TITLE
Is it possible to use microsoft-r-open in opencpu docker?

### ISSUE THREAD

**Issue by nainai123** [opencpu/opencpu#382]
I installed microsoft-r-open in opencpu but I found that microsoft-r-open is not used after I opened the web test tool Why?
![image](https://user-images.githubusercontent.com/88811792/129314250-8570e734-0131-4186-af64-1f9ab3ba4a5e.png)

**Comment by jeroen** [comment]
We don't support Microsoft R. Also Microsoft has stopped developing MS open R and recommends you use regular R.
