### ISSUE TITLE
Update rstudio-server version in Launchpad PPA

### ISSUE THREAD

**Issue by jdblischak** [opencpu/opencpu#387]
Hi @jeroen, thanks so much for OpenCPU. I've found it useful not only for creating web apps, but also for using R on Windows. Specifically I run opencpu-server and rstudio-server from the WSL as [first described by David Smith](https://blog.revolutionanalytics.com/2017/12/r-in-the-windows-subsystem-for-linux.html) (see my [blog post](https://blog.jdblischak.com/posts/wsl-r/) more details on my personal setup).

Unfortunately, when the graphics engine was bumped to 14 with the [release of R 4.1.0](https://cloud.r-project.org/doc/manuals/r-release/NEWS.html), the plots pane in rstudio-server stopped working:

```R
> plot(1)
Warning message:
R graphics engine version 14 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

You updated all the OpenCPU Docker images from rstudio-server 1.3 to 1.4 in https://github.com/opencpu/opencpu-server/commit/bb75b8016074ba39db304ada1924c91e268a18c5. However, the Launchpad PPAs [opencpu-2.2](https://launchpad.net/~opencpu/+archive/ubuntu/opencpu-2.2) and [opencpu-dev](https://launchpad.net/~opencpu/+archive/ubuntu/opencpu-dev) both still list rstudo-server 1.3.953. And on my Ubuntu 18.04 WSL, this actually installs version 1.3.95**9**.

```sh
$ apt list -a rstudio-server
Listing... Done
rstudio-server/bionic,now 1.3.953-bionic1 amd64 [installed]

$ rstudio-server version
1.3.959 (Middlemist Red) for Ubuntu Bionic
```

Would it be possible to update rstudio-server to version 1.4+ on Launchpad?

**Comment by jeroen** [comment]
OK I have updated them to the latest version. Thanks for the tip.
