### ISSUE TITLE
add more recent "arrow" format for outputs ?

### ISSUE THREAD

**Issue by behrica** [opencpu/opencpu#395]
It seems that the "feather" format opencpu support for outputs is rather deprecated.
(at least the version which is produced bye feather::write_feather)
I think opencpu should add an other format of  the "arrow" family as a output format.

**Comment by jeroen** [comment]
Added this in opencpu 2.2.7:

 - https://cloud.opencpu.org/ocpu/library/MASS/data/cats/arrowipc
 - https://cloud.opencpu.org/ocpu/library/MASS/data/cats/feather
 - https://cloud.opencpu.org/ocpu/library/MASS/data/cats/parquet
