### ISSUE TITLE
Adding windows fonts (such as Impact) to opencpu cloud server.

### ISSUE THREAD

**Issue by annafergusson** [opencpu/opencpu#397]
It seems that the windows fonts (such as the memeable *Impact*) are no longer available on the cloud server. 

_Originally posted by @annafergusson in https://github.com/opencpu/opencpu/issues/375#issuecomment-1058001525_

**Comment by annafergusson** [comment]
I know it's not an important issue at all but if there were anyway to bring back the windows fonts to the opencpu cloud server, I would be extremely grateful 😹😹

**Comment by jeroen** [comment]
Ok sorry about that, can you try again, it should be fixed now.

**Comment by annafergusson** [comment]
Thanks so much Jeroen! ✔️✔️
