### ISSUE TITLE
Package or namespace load failed : rlang

### ISSUE THREAD

**Issue by rgr** [opencpu/opencpu#398]
Hi,

after I built my docker image I now get the following error I didn't have before when I call the image API : 

```
package or namespace load failed for 'kitten' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace 'rlang' 0.4.11 is already loaded, but >= 1.0.0 is required
```

I tried adding the package in the installer but to no avail 

```
# Use the official OpenCPU Dockerfile as a base
FROM opencpu/base:v2.2.5

# Move OpenCPU configuration files into place
COPY docker/opencpu_config/* /etc/opencpu/

# Copy and run our custom install script for R dependencies
WORKDIR /usr/local/src
COPY docker/installer.R /usr/local/src/app/docker/installer.R
RUN /usr/bin/R --vanilla -f app/docker/installer.R

# Copy our R code into the container
COPY . /usr/local/src/app

# Install our code as an R package on the server
RUN tar czf /tmp/kitten.tar.gz app/ \
  && /usr/bin/R CMD INSTALL /tmp/kitten.tar.gz
```

installer.R
```
install.packages("rlang", repos = repo, dependencies = TRUE, Ncpus = 4)
```

How do I go updating rlang to the last version ? Is it something to do with how opencpu works ?

Thanks !

**Comment by jeroen** [comment]
Try building from the latest version, i.e. change your first line to:

```
FROM opencpu/base:latest
```
or
```
FROM opencpu/base:v2.2.7
```

**Comment by rgr** [comment]
I tried tu update the image too but I still have the same problem...

**Comment by jeroen** [comment]
You must have done something wrong because the latest image has rlang 1.0.1

**Comment by rgr** [comment]
well I didn't change anything to my codebase besides the docker file opencpu version and then I came back to 2.2.5 when it didn't work.

Could it be a local cache of docker that pulls the wrong image ? I'll try to build it with latest instead of a tag...

**Comment by jeroen** [comment]
Maybe you need to `docker pull opencpu/base` to get the latest `latest` tag?

**Comment by rgr** [comment]
I tried that and it works :) 

I don't know what happened... Thanks for the help !
