### ISSUE TITLE
GET Requests and Dynamic Content 

### ISSUE THREAD

**Issue by dansmith01** [opencpu/opencpu#399]
I'd like to use opencpu to pull records from an SQL database.

For example, the URL `https://mysite.com/download?file=foo.json&token=baz` would run an R function to pull the records from the database and hand just the dynamically generated file contents back to the user.

This is simple enough with opencpu and a POST request, but as far as I can tell, it isn't possible with a simple "click me to download" hyperlink.

Would you consider adding a configuration option to always run functions instead of returning the function's code? Or a special GET parameter such as `eval=T`/`eval=F` for overriding the default behavior?

I wouldn't mind putting together a pull request for a feature like this, if you're okay with incorporating it.

**Comment by jeroen** [comment]
We can't do that, this would violate the http standard. GET is [safe and idempotent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) so it is not appropriate to invoke dynamic code on the server.
