### ISSUE TITLE
Error with permissions when a function is used to call 'rmarkdown::render' that creates an html report. 

### ISSUE THREAD

**Issue by ltrainstg** [opencpu/opencpu#404]
# Problem 
I'm trying to write a simple function that creates a couple tables in rmarkdown by passing data to openCPU.
I get an error about permission denied.

How can I give openCPU permission to connect to the intermediary file created by RMarkdown in order to create reports from given data.  I am aware of the running scripts and reproducible documents api, do I just have to use those instead of the 'rmarkdown' library? 

I like using rmarkdown::render or do you recommend just using pandoc/knitr directly using the API call?

 

## Exact Error 
```
Warning message:
cannot open file 'test.knit.md': Permission denied
Error:
cannot open the connection
```

## The function 
```
testReport <- function(...){
  library(rmarkdown)
  rmd_file<- system.file('test.Rmd', package = 'testPackage')
  render(rmd_file)
}

```

**Comment by jeroen** [comment]
I think the problem is that knitr writes (temporary) files in the same dir as the source Rmd file, however you don't have permission to write in the installation directly of the package installation. Try rendering the file from the working directory:


```r
testReport <- function(...){
  library(rmarkdown)
  rmd_file<- system.file('test.Rmd', package = 'testPackage')
  file.copy(rmd_file, ".")
  render('test.Rmd')
}

```

**Comment by ltrainstg** [comment]
Yes that works. Thank You.
