### ISSUE TITLE
opencpu-server version mismatch and PPA update

### ISSUE THREAD

**Issue by jdblischak** [opencpu/opencpu#407]
* I noticed that the most recent release of opencpu-server was [2.8.8-6](https://github.com/opencpu/opencpu-server/releases/tag/v2.8.8-6), while the R package remains 2.2.8. Was this a typo?
* RStudio Server was recently bumped to version 2022.07.2-576 in commit https://github.com/opencpu/opencpu-server/commit/c91b77a02070db3bb0a2a325211a2dbe854362ca. Could you please also update the [PPA](https://launchpad.net/~opencpu/+archive/ubuntu/opencpu-2.2)? Thanks!

**Comment by jeroen** [comment]
The `-6` postfix indicates rebuilds of the cloud server, they are the same R package. I'll have a look at rstudio.

**Comment by jdblischak** [comment]
> The -6 postfix indicates rebuilds of the cloud server with updated dependencies, they are the same version of the R package.

I was referring to the minor version: 2.<u>_**2**_</u>.8 != 2._**8**_.8

> I'll have a look at rstudio.

Thanks!

**Comment by jeroen** [comment]
Oh oops that was a typo!

**Comment by jdblischak** [comment]
Thanks for updating rstudio-server in the PPA. Are you still supporting Bionic? As far as I can tell, [RStudio itself still supports it](https://github.com/rstudio/rstudio/wiki/Installing-RStudio-Dependencies). It's fine if you no longer want to support Bionic; I just wanted to ask since I'd use it if you uploaded it

![image](https://user-images.githubusercontent.com/1608317/198047089-c6d193d3-cd95-4e74-bcbd-ecb6f4c15a24.png)

**Comment by jeroen** [comment]
Sorry I don't, two systems is enough support :) GitHub is dropping bionic later this year, and it will be EOL in a few months: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by jdblischak** [comment]
No worries! I totally understand. I am also phasing out use of Bionic across my various computers/projects. I am only going to be using the computer in which I use your PPA for a few more months, so I am not bothering to update it
