### ISSUE TITLE
opencpu server - rlang update needed?

### ISSUE THREAD

**Issue by badgettrg** [opencpu/opencpu#408]
Hi Jeroen

I am getting the following error at https://qitools.ocpu.io/positivedeviance/www/ 

"namespace 'rlang'1.0.5 is already loaded, but >= 1.06 is required" 

Per https://cran.r-project.org/web/packages/rlang/ , rlang updated to 1.06 on 09//24/2022.

I do not think I can force that update?

thanks

**Comment by jeroen** [comment]
Are you using the docker image? You should be able to upgrade to the latest version easily:

```sh
sudo apt-mark unhold opencpu-server
sudo apt-get update
sudo apt-get upgrade
```

**Comment by badgettrg** [comment]
Have not used docker before. Looking at https://www.opencpu.org/posts/opencpu-with-docker/ , seems docker would only let me upgrade my own server, whereas I need to update the rlang library your server at opencpu.org

**Comment by rgr** [comment]
I have the same problem with rlang and tidyselect depending on which version of Opencpu I use (2.2.5 to 2.2.8-6). 

I tried updating the different lib path inside the image but even when every lib path has the latest version of the package, it still tells me its loading and older version from the namespace... I don't understand anymore.

@jeroen I tried your solution but it didn't work for me.

**Comment by rgr** [comment]
@jeroen Thanks for the 2.2.8-7 update. Works for me :)

**Comment by jeroen** [comment]
Thanks:)

**Comment by badgettrg** [comment]
ocpu.io still gives an rlang error:

[cid:b0e8aebd-2f0b-4bea-a724-46d79cbb14fc]
________________________________

**Comment by jeroen** [comment]
Ah let me upgrade the production server, one sec....

**Comment by stefvanbuuren** [comment]
Late on the table, but perhaps a next time you could try the solution from #327 to evade version clash:

```
remove.packages("thepackage", "/usr/lib/opencpu/library")
```

**Comment by rgr** [comment]
@stefvanbuuren thanks for the idea. I tried to remove and update all the packages that were causing problems in different libpath but sometimes even with the package not installed I got the message that a previous version was loaded. With the issue you reference I now understand there are more "hidden" libpath for opencpu that I didn't see... explaining my problem !
