### ISSUE TITLE
Latest OpenCPU version with legacy R version

### ISSUE THREAD

**Issue by sprudel79** [opencpu/opencpu#417]
Hi everyone,
I would like to use latest OpenCPU-server version (2.2.8) but I need to run code from R packages created with R version 3.6.3.
As I am aware OpenCPU targets already R 4.X.
What would be the best way to achieve this? What I have tried already is to create my own Ubuntu 22.04 Docker image with R 3.6.3 installed from source code. But how can I add OpenCPU to it then?
Thanks in advance.

**Comment by jeroen** [comment]
I think that will be difficult because apache is configured against the version of `r-base` in that system.

One thing we could do is create an image based on ubuntu 20.04 which ships with R-3.6.3 by default: https://packages.ubuntu.com/focal/r-base

**Comment by sprudel79** [comment]
Thanks @jeroen for your quick reply, I'll give it a try next week.
