### ISSUE TITLE
Call Rmardown file with htmlwidgets, got "Error in loadNamespace(name): there is no package called 'webshot'"

### ISSUE THREAD

**Issue by GQ0308** [opencpu/opencpu#418]
Hi, I'm new to OpenCPU and trying to make my first package. I would like to generate a html report  with plotly graph, based on markdown, with parameters.

So I copied knitr-minimal.Rmd example to my package and add following to the file, to plot with plotly.
```{r, plotly=TRUE, message=FALSE}
library(plotly)
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species, colors = "Set1")
```

I could call the endpoit successfully.
![image](https://user-images.githubusercontent.com/11734538/224940317-599559f2-f6f8-44cf-8f18-4b4a10b33100.png)
But when I check the html file in the temp session, I got an 'webshot' error.
![image](https://user-images.githubusercontent.com/11734538/224940937-ecb77b06-d946-43ee-95ef-e264abd5098c.png)

Then I tried to render the Rmd file with following commands just like what does in OpenCPU execute_file.R.
```
knit('knitr-minimal.Rmd')
knitr::pandoc('knitr-minimal.md')  
```
I saw same error in generated html file.

Maybe this is something wrong with mypackage? Any help is appreciated, thanks.

**Comment by jeroen** [comment]
It looks like `plotly` needs the `webshot` package for what you are trying to do, however plotly does not have a hard dependency on `webshote`.

Perhaps you can add `Imports: webshot` to your package, to make sure it is available.

**Comment by GQ0308** [comment]
Thanks, I realized this question is out of scope. I got it work by calling rmarkdown::render function.
