### ISSUE TITLE
ocpu.io domain timing out?

### ISSUE THREAD

**Issue by badgettrg** [opencpu/opencpu#420]
Including the demo apps at https://cran.ocpu.io/nabel/www/ . I updated an HTML page last night at https://github.com/qitools/charts/blob/master/inst/www/index.html . I initially used https://public.opencpu.org/ocpu/webhook but have also used https://cloud.opencpu.org/ocpu/webhook. Please let me know if I need to change my workflow if I am causing this.

**Comment by jeroen** [comment]
Thanks. I restarted the server and now it's back. Looks like the cheaper host that I switched to isn't as reliable :(
