### ISSUE TITLE
Opencpu error

### ISSUE THREAD

**Issue by badgettrg** [opencpu/opencpu#426]
Users at two different subdomains at ocpu.io are getting the same error. Thanks

openrules.ocpu.io says
Server error: package or namespace load failed for 'home' in
dyn.load(file, DLLpath = DLLpath,
unable to load shared object '/usr/local/lib/opencpu/apps/
ocpu_github_openrules_home/stringi/libs/stringi.so':
cannot open shared object file: No such file or
directory

**Comment by badgettrg** [comment]
I think I have this fixed based on https://forum.posit.co/t/tidyverse-loading-giving-error/125956 and seeing that the package https://cran.r-project.org/web/packages/stringi/ was modified at cran a few days ago. 

I never had needed a statement in my namespace for import(stringi), but adding that now fixed the problem.

**Comment by jeroen** [comment]
Thanks. I upgraded the server to ubuntu 24.04 but some packages need to be rebuild for this.
