### ISSUE TITLE
installing v8 in opencpu results in "child process has died" error in minimal docker file. 

### ISSUE THREAD

**Issue by ltrainstg** [opencpu/opencpu#428]
# Problem 
I use V8 via DiagrammeRSVG to help create an image. I kept getting an error and I think it has to do with the V8 package. Since I think you authored both, maybe the fix is simple? I'd like them to work out of the box since I think there are several open tickets that all kind of revolve around this, but I can't determine what was done to resolve those if it is the same thing. 

# Reproducing
1. Build docker file at port 80 
2. curl http://localhost/ocpu/library/V8/R

Dockerfile:  
```
FROM opencpu/rstudio
RUN Rscript -e "install.packages('V8')"
RUN R --version && id
```

Error:
```
child process has died

In call:
tryCatch({
    if (length(priority)) 
        setpriority(priority)
    if (length(rlimits)) 
        set_rlimits(rlimits)
    if (length(gid)) 
        setgid(gid)
    if (length(uid)) 
        setuid(uid)
    if (length(profile)) 
        aa_change_profile(profile)
    if (length(device)) 
        options(device = device)
    graphics.off()
    options(menu.graphics = FALSE)
    serialize(withVisible(eval(orig_expr, parent.frame())), NULL)
}, error = function(e) {
    old_class <- attr(e, "class")
    structure(e, class = c(old_class, "eval_fork_error"))
}, finally = substitute(graphics.off()))
```

## Related Tickets

https://github.com/jeroen/V8/issues/136
https://github.com/opencpu/opencpu/issues/366

## Additional Error log

```
da_opencpu.1.bxrdkasp1usf@admin    | 
da_opencpu.1.bxrdkasp1usf@admin    | 
da_opencpu.1.bxrdkasp1usf@admin    | #
da_opencpu.1.bxrdkasp1usf@admin    | # Fatal error in , line 0
da_opencpu.1.bxrdkasp1usf@admin    | # Fatal process out of memory: Failed to reserve virtual memory for process-wide V8 pointer compression cage
da_opencpu.1.bxrdkasp1usf@admin    | #
da_opencpu.1.bxrdkasp1usf@admin    | #
da_opencpu.1.bxrdkasp1usf@admin    | #
da_opencpu.1.bxrdkasp1usf@admin    | #FailureMessage O

```

### Misc
There is something going on with memory here and I don't know what.
I know it can run since our company did it before, but the sys admin left and we are trying to dockerize the environment instead of just having an instance running.

**Comment by jeroen** [comment]
I think you have to avoid pre-loading the V8 package. Do you have any packages preloaded in your config?

**Comment by jeroen** [comment]
Can you try to raise the `rlimit.as` config? Either edit `/etc/opencpu/server.conf` or create a dockerfile like so:

```
FROM opencpu/rstudio
RUN Rscript -e "install.packages('V8')"
RUN R --version && id
RUN echo '{"rlimit.as":1e10}' > /etc/opencpu/server.conf.d/memory.conf
```
