### ISSUE TITLE
Write to log files

### ISSUE THREAD

**Issue by jeroen** [opencpu/opencpu#47]
OpenCPU server log files for:
- Package installations:
  - webhook build: success/fail
  - install_github: success/fail
  - install cran/bioc: success/fail
- POST requests: what, payload (except for multipart), success
- GET what, success

**Comment by timraasveld** [comment]
@jeroenooms do you see any chance of implementing logging soon? We at RoQua would like to know what arguments are actually sent to the called R library, and what the raw return values are.

If you don't see a chance, one of us might pick up this ticket. I think the correct place for putting the log statements would be in [the eval handler](https://github.com/jeroenooms/opencpu/blob/master/R/session.R#L46)?
And would you like to always have calls logged, or add it as a configuration parameter?

**Comment by jeroenooms** [comment]
I don't have time to implement this any time soon, but feel free to have a go at it.

Can you spell out your use case? What exactly do you need to log? Things you log inside the eval handler can only log progress of function you are calling, no system stuff. I.e. it won't log clients that request an invalid URL or so.

**Comment by timraasveld** [comment]
We need to log the STDOUT output of the R package that has been called, which I suspect is possible using the `evaluate` package you use in OpenCPU. This is needed because our package behaves differently in production (ran through OpenCPU) compared to when we run it locally using R directly.

My suggestion is that we take these steps in a PR:
1. Add an option to debug in the configuration
2. Log all output of each request to `/var/log/opencpu/debug.log`
3. Add logrotate.d configuration to prevent the log file getting too big

**Comment by jeroenooms** [comment]
OpenCPU already captures the stdout and makes it a available through the API. So you would like to duplicate this output by wiring it to a log file as well? What do you gain from this?

**Comment by timraasveld** [comment]
I didn't know that!

There are two reasons to want to log stdout to a separate file:

- We use the `/library/package/R/function/json` format, which doesn't contain any reference to the tmp files
- We run OpenCPU in a distributed setup (two servers + load balancer), so there's no way to garuantee that request A (that initiates the computation) is handled by the same server as request B (which would be to obtain the stdout log)

**Comment by SinanGabel** [comment]
Hi!

Load balancer, same client:

You may want to see "ip_hash" for nginx:

http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash


Br,
Sinan

**Comment by timraasveld** [comment]
@SinanGabel Thanks for the suggestion. However, we have one application server that talks to multiple OpenCPU instances, so I think choosing a server based on IP is no option for us.
