### ISSUE TITLE
Server error: R call did not return within 90 seconds. Terminating process.  In call: NULL

### ISSUE THREAD

**Issue by nickytong** [opencpu/opencpu#78]
Hello Jeroen,

Thanks for writing the amazing opencpu package. I wrote a small app that did computations around 10min before generating the result. However, I get the error:

Server error: R call did not return within 90 seconds. Terminating process.  In call: NULL

I'm running the app locally through R GUI. I wonder if we can extend the time limit?

Thank you very much,

Pan

**Comment by slfan2013** [comment]
Hi @jeroen ,
For the new opencpu, it says that 
```
Loading config from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/opencpu/config/defaults.conf
Loading config from /Users/silifan/Library/Application Support/opencpu/user.conf
Welcome to OpenCPU!
```

If I would like to change the timeout setting from the 90s to 900s, which file do I use to change the `"timelimit.post": 90`? These two files look identical to me.

**Comment by jeroen** [comment]
The second one. The first has the defaults and the second file has your custom configs.
