### ISSUE TITLE
Missing dependency to RCurl in ppa:opencpu/opencpu-1.2

### ISSUE THREAD

**Issue by jdanielnd** [opencpu/opencpu#90]
I'm trying to install a stand-alone version of OpenCPU in Ubuntu 12.04 LTS (also tried on   Ubuntu 13.10) but the server was not responding and the /var/log/apache2/error.log shows the following errors:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/opencpu/library/RCurl/libs/RCurl.so':
  libcurl.so.4: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘opencpu’
 From directive RHandler on line 12 of /etc/apache2/sites-enabled/opencpu.
```

I tried opening R and loading RCurl, but I found out it was not installed. I tried installing it and got `ERROR: configuration failed for package 'RCurl'`. So I used

```
sudo apt-get install libcurl4-openssl-dev
```

to install the missing library and was able to install RCurl. I restarted OpenCPU and everything was working fine. Maybe is a system specific problem (although I was installing from a fresh new cloud), but this dependency was missing and messing with the required packages.

**Comment by manueltimita** [comment]
Relative to this issue, I encountered something similar today, with the latest OpenCPU release on Ubuntu 14.04 LTS. Not sure that adding `libcurl3` as a dependency has fixed the problem. 

The same `ERROR: configuration failed for package ‘RCurl’` happens when trying to install `httr` or `RCurl`. In my case it turns out that it needed the curl-dev package: `sudo apt-get install libcurl4-openssl-dev`

Btw, OpenCPU is truly awesome!

**Comment by jeroenooms** [comment]
The `RCurl` package should come preinstalled with opencpu. No need to reinstall it, unless you are building opencpu from source. Can you help me explain when the problem appears?

**Comment by manueltimita** [comment]
The problem simply appears when trying to `> install.packages("httr")`, as `httr` depends on `RCurl`. It fails with the error `ERROR: configuration failed for package ‘RCurl’`. If you then `sudo apt-get install libcurl4-openssl-dev`, and try again to install `httr` in R, this time the installation succeeds.
